adobe/express-website

- express/blocks/hero-image/hero-image.css
- express/blocks/hero-image/hero-image.js
ermhh.. :)
https://hero-image-block--express-website--adobe.hlx3.page/drafts/uncled/signin-blocker
vs. 
https://main--express-website--adobe.hlx3.page/express/signin-status
> chore: add hero image block

- express/blocks/hero-animation/hero-animation.js
https://hero-animation-block--express-website--adobe.hlx3.page/drafts/uncled/index1?lighthouse=on
https://hero-animation-block--express-website--adobe.hlx3.page/express/?lighthouse=on
> feat: add hd breakpoint

- express/blocks/hero-animation/hero-animation.js
- express/scripts/scripts.js
excluding martech completely when lighthouse is on...
https://better-lighthouse-check--express-website--adobe.hlx.live/express/?lighthouse=on
vs. 
https://main--express-website--adobe.hlx.live/express/?lighthouse=on
> chore: better lighthouse check

- express/blocks/columns/columns.css
Re-made the pull request https://github.com/adobe/express-website/pull/286 because of the new webistry fork after release.
- Fixes https://github.com/adobe/express-website-issues/issues/298
Also fixes part 1 of https://github.com/adobe/express-website-issues/issues/299
> fix(columns): fix paddings, replace max-width with min-width, fix highlight columns padding

- express/blocks/cards/cards.css
- express/blocks/template-list/template-list.css
- Cards width bug fixed
- Added a missing margin in cards
- Templates masonry grid is now centered
- Fixes https://github.com/adobe/express-website-issues/issues/299
> fix(bug-list): fix small bug in cards and templates masonry

- express/blocks/inline-banner/inline-banner.css
Before: https://main--express-website--adobe.hlx3.page/education/express/
After: https://inline-banner-mobile--express-website--adobe.hlx3.page/education/express/
> fix(inline-banner): mobile alignment

- express/blocks/blog-posts/blog-posts.js
Added language specific "Read More"  text to Blogs CTA.
Read More
En savoir plus (fr)
もっと見る (jp)
Mehr dazu (de)
https://main--express-website--lamontacrook.hlx3.page/express/learn/blog?lighthouse=on
https://main--express-website--lamontacrook.hlx3.page/jp/express/learn/blog?lighthouse=on
vs. 
https://main--express-website--adobe.hlx3.page/express/learn/blog
> Add Read More CTA

- express/scripts/scripts.js
https://price-format-fix--express-website--adobe.hlx3.page/express/pricing?country=th&martech=off
vs.
https://www.adobe.com/express/pricing?country=th
> fix(price): regression in THB display

- express/blocks/banner/banner.css
- express/blocks/banner/banner.js
- test/unit/blocks/blocks-test-list.js
- test/unit/blocks/expected/banner.multi-button.block.html
- test/unit/blocks/input/banner.multi-button.doc.html
Fix https://github.com/adobe/express-website-issues/issues/309
https://issue-309--express-website--adobe.hlx3.page/drafts/rofe/columns-test?martech=off
vs
https://main--express-website--adobe.hlx3.page/drafts/rofe/columns-test
> feat(banner): side by side buttons

- express/blocks/columns/columns.css
- express/scripts/scripts.js
https://icon-fix--express-website--adobe.hlx3.page/drafts/rofe/columns-test?martech=off
vs
https://main--express-website--adobe.hlx3.page/drafts/rofe/columns-test
> Icon fixes

- express/scripts/scripts.js
https://jira.corp.adobe.com/browse/DOTCOM-54359
https://price-format-sar--express-website--adobe.hlx3.page/express/pricing?country=sa
vs
https://main--express-website--adobe.hlx3.page/express/pricing?country=sa
> fix(pricing): SAR formatting doesn't match commerce system

- express/blocks/how-to-steps/how-to-steps.js
Fix https://github.com/adobe/express-website-issues/issues/314
https://main--express-website--adobe.hlx3.page/drafts/nipun/education-deployment
vs
https://issue-314--express-website--adobe.hlx3.page/drafts/nipun/education-deployment?lighthouse=on
> feat(how-to-steps): rich formatting inside steps

- express/blocks/shared/video.js
- express/blocks/tutorials/tutorials.js
https://main--express-website--adobe.hlx3.page/drafts/nipun/education-deployment
vs
https://video-resilience--express-website--adobe.hlx3.page/drafts/nipun/education-deployment?lighthouse=on
> fix(tutorials): fail gracefully on invalid url

- express/blocks/columns/columns.css
- express/blocks/template-list/template-list.css
https://main--express-website--adobe.hlx3.page/drafts/nipun/grow-customer-relationship
vs
https://single-col-tweak--express-website--adobe.hlx3.page/drafts/nipun/grow-customer-relationship?lighthouse=on
> fix(columns): optimize width for single column

- express/blocks/columns/columns.js
Fix: https://github.com/adobe/express-website-issues/issues/316
https://main--express-website--adobe.hlx3.page/drafts/rofe/columns-test
vs
https://issue-316--express-website--adobe.hlx3.page/drafts/rofe/columns-test?lighthouse=on
> fix(columns): social icon misaligned in safari

- express/blocks/link-list/link-list.css
- express/scripts/scripts.js
Fix: https://github.com/adobe/express-website-issues/issues/317
https://issue-317--express-website--adobe.hlx3.page/drafts/rofe/columns-test?lighthouse=on
> feat(link-list): add center option

- express/blocks/columns/columns.css
- express/blocks/columns/columns.js
- express/blocks/promotion/promotion.js
- express/blocks/shared/video.js
- express/blocks/tutorials/tutorials.css
- express/blocks/tutorials/tutorials.js
Fix https://github.com/adobe/express-website-issues/issues/312
https://main--express-website--adobe.hlx3.page/drafts/rofe/video
vs
https://issue-312--express-website--adobe.hlx3.page/drafts/rofe/video?lighthouse=on
> feat(video): promotional content

- express/blocks/pricing-columns/pricing-columns.css
- express/scripts/scripts.js
Added the single column variable to the pricing-columns block.
https://pricing_columns_single--express-website--webistry-development.hlx3.page/drafts/williambsm/pricing
> Pricing columns single

- express/blocks/animation/animation.js
brush up broken animation block...
> chore: brush up ancient animation block

- express/blocks/columns/columns.css
- express/styles/styles.css
Fix https://github.com/adobe/express-website-issues/issues/319
https://main--express-website--adobe.hlx3.page/drafts/rofe/video
vs
https://issue-319--express-website--adobe.hlx3.page/drafts/rofe/video?lighthouse=on
> fix(columns): use 1122px in fullsize on desktop

- express/scripts/scripts.js
Fix https://github.com/adobe/express-website-issues/issues/324
https://issue-324--express-website--adobe.hlx3.page/drafts/rofe/video?lighthouse=on 
Look for:
> feat: open external links in a new window

- express/blocks/hero-animation/hero-animation.css
- express/scripts/scripts.js
Fix: https://github.com/adobe/express-website-issues/issues/326
https://issue-326--express-website--adobe.hlx3.page/drafts/rofe/hero-dark?lighthouse=on
> feat(hero-animation): dark option

- express/blocks/columns/columns.css
- express/blocks/columns/columns.js
Added a thumbnail to the image to indicate that there is a playable video.
https://github.com/adobe/express-website-issues/issues/322
https://ccx_video_thumbnail--express-website--webistry-development.hlx3.page/drafts/williambsm/registration
I have my reservations about using setTimeout to delay the thumbnail injection, but the reason it is there for now is to account for blocks where the video column is attributed before the picture column.
> Ccx video thumbnail

- express/blocks/hero-animation/hero-animation.js
Allowing the loop to be disabled via a url search parameter.
https://github.com/adobe/express-website-issues/issues/321
With loop:
https://marquee_loop_stop--express-website--webistry-development.hlx3.page/drafts/nipun/ticket-update/express/
Without loop:
https://marquee_loop_stop--express-website--webistry-development.hlx3.page/drafts/williambsm/marquee-loop
> feat(hero-animation): allow turning off loop

- express/blocks/shared/video.js
https://main--express-website--adobe.hlx3.page/drafts/nipun/ticket-update/express/
vs
https://video-close--express-website--adobe.hlx3.page/drafts/nipun/ticket-update/express/?lighthouse=on
(press "play the video")
> feat(video): add close button to overlay

- express/styles/styles.css
https://main--express-website--adobe.hlx3.page/drafts/nipun/registration
vs
https://ccx-stacked--express-website--adobe.hlx3.page/drafts/nipun/registration?lighthouse=on
> chore: special styling for ccx stacked logo

- express/scripts/delayed.js
https://region-based-redirect--express-website--adobe.hlx3.page/express/?lighthouse=on
redirect to region specific homepage based on region filters
> chore: region based redirect

- express/scripts/legacy-browser.js
- head.html
https://legacy-browser--express-website--adobe.hlx3.page/kr/express/?legacy=on
https://legacy-browser--express-website--adobe.hlx3.page/jp/express/?legacy=on
https://legacy-browser--express-website--adobe.hlx3.page/express/?legacy=on
> chore: legacy browser redirect

- express/blocks/columns/columns.css
Fix: https://github.com/adobe/express-website-issues/issues/331
Test Url: https://issue-331--express-website--webistry-development.hlx3.page/express/feature/video/convert/avi-to-mp4
> fix(columns): fix regression full-size columns

- express/scripts/scripts.js
https://region-selector-update--express-website--adobe.hlx3.page/express/feature/quick-actions
i don't think this can be tested easily without being deployed into prod...
> chore: region selector update

- express/blocks/submit-email/submit-email.js
Stress test Adbe X Meta subscribe form.
Details
- Simulate 100,000 signups
- Sign ups happen continuously to the max that can be sent in 1 minute (2000).
- 30ms delay between each POST
> test: Adbe x Meta stress test (1000) messages

- express/blocks/columns/columns.js
- express/scripts/scripts.js
- Fix: https://github.com/adobe/express-website-issues/issues/334
- Test URL: https://issue-334-floatybtn--express-website--webistry-development.hlx3.page/express/create/logo
I had to move the intersection observer into the scripts.js file so that I can await and run the function only after the block is finished loading, to be sure that the intersection observer is accurate on page load.
> fix(fixed-button): fixed-button will appear if the title is too long on page load

- express/blocks/columns/columns.js
- express/blocks/tutorials/tutorials.js
Fix: https://jira.corp.adobe.com/browse/DOTCOM-59299
Test URL: https://dotcom-59299--express-website--adobe.hlx3.page/express/?lighthouse=on
> fix: js error in private safari

- express/blocks/template-list/template-list.js
- test/unit/blocks/expected/template-list.sixcols.block.html
- test/unit/blocks/input/template-list.title.doc.html
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/template-list
- After: https://template-list-resilience--express-website--adobe.hlx.page/drafts/rofe/template-list?lighthouse=on
> fix(template-list): ignore formatting in 2nd column

- express/scripts/scripts.js
Test URLs:
- Before: https://main--express-website--adobe.hlx3.page/express/
- After: https://express-dev--express-website--adobe.hlx3.page/express/
> chore: express dev

- express/blocks/submit-email/submit-email.css
@timliu-adobe requested more padding on mobile for the subscription block
Test URL: https://submit-email-block--express-website--adobe.hlx.page/drafts/nipun/registration
> fix: add email signup block padding on mobile

- express/blocks/inline-banner/inline-banner.css
- express/blocks/inline-banner/inline-banner.js
Fix https://github.com/adobe/express-website-issues/issues/339
Test URL: https://h4-inline-banner--express-website--adobe.hlx.page/drafts/nipun/registration?lighthouse=on
> feat: allow h4 in inline-banner

- express/blocks/template-list/template-list.js
There is no issue attached to this.  It was a follow up request in Slack.
To view this feature, simulate a mobile screen size while at the top of the page.  A small button with a bouncing arrow should appear.  The new tracking should contain "scrollbuttonPressed"
Test URLs:
- Before: https://main--express-website--adobe.hlx3.page/express/create/flyer
- After: https://ccx0022tracking--express-website--adobe.hlx3.page/express/create/flyer?lighthouse=on
> Ccx0022tracking

- express/blocks/columns/columns.css
Fix #340 
https://main--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/express-your-fandom
vs
https://issue-340--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/express-your-fandom?lighthouse=on
> feat: place images above h1 in fullsize columns

- express/blocks/template-list/template-list.js
- express/scripts/instrument.js
This is a preparatory PR to add better analytics tracking for the MLB page.
Branch changes are mininal but can be tested here:
https://mlb_analytics--express-website--webistry-development.hlx3.page/drafts/Ankush%20hcl37284/express-your-fandom
The only requirement that couldn't be satisfied was tracking the different "Get Started" CTA's, as I'm not sure how we could target them individually in order to give them a more in dept value.
> Mlb analytics

- express/blocks/blog-posts/blog-posts.js
https://category-filter--express-website--adobe.hlx.page/drafts/uncled/news
> chore: add category filter

- 404.html
https://main--express-website--adobe.hlx.page/fr/express/learn/blog/101-brilliant-color-combinations
vs.
https://404-update--express-website--adobe.hlx.page/fr/express/learn/blog/101-brilliant-color-combinations
> chore: 404 update

- express/blocks/columns/columns.css
https://main--express-website--adobe.hlx.page/express/learn/express-your-brand
vs
https://columns-video-overlay--express-website--adobe.hlx.page/express/learn/express-your-brand?lighthouse=on
> chore(columns): always show play button

- express/blocks/promotion/promotion.js
- express/scripts/instrument.js
Test URL:
https://eyb_analytics--express-website--webistry-development.hlx3.page/express/learn/express-your-brand
> Express Your Brand analytics

- express/blocks/hero-animation/hero-animation.js
- image only support
- optimize poster image
https://poster-only--express-website--adobe.hlx.page/drafts/rofe/holly-and-co?lighthouse=on
vs
https://main--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-62499/holly-and-co
> feat(hero-animation): also work with just poster

- express/blocks/shared/video.js
- express/scripts/instrument.js
Test URL:
https://video-analytics--express-website--webistry-development.hlx3.page/express/learn/express-your-brand?lighthouse=on
You can use this url or any other url that contains a video that uses the video block and is an HTML 5 video.
Video analytics can be controlled by modifying the contents of the express/video-analytics.xlsx file at the root folder.
Fix: https://github.com/adobe/express-website-issues/issues/343
> Video analytics

- express/blocks/ratings/ratings.js
https://ratings-desc--express-website--adobe.hlx.page/express/feature/image/remove-background?lighthouse=on
> chore: add description to ratings schema

- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
Fix the floating button to hide when it intersects with the footer
Test URL:
- https://floatin-btn-fix--express-website--webistry-development.hlx.page/drafts/solene/feature?lighthouse=on
> fix(floating-button): hide button when intersects with the footer

- express/styles/styles.css
Attempt to fix CLS issues that appear from the floating button:
- Hide floating button before css loads
- Hide the section-wrapper that ONLY has the floating-button block
Test URL:
- https://performance-fix-button--express-website--webistry-development.hlx.page/drafts/rofe/home?lighthouse=on
> fix(floating-button): CLS issues for floating button

- express/blocks/make-a-project/make-a-project.css
- express/blocks/make-a-project/make-a-project.js
- express/blocks/shared/carousel.css
- express/blocks/shared/carousel.js
- express/blocks/template-list/template-list.css
Fix: https://jira.corp.adobe.com/browse/MWPW-111363
Test URLs:
- Before: 
https://main--express-website--adobe.hlx3.page/drafts/rofe/home1
https://main--express-website--adobe.hlx3.page/drafts/rofe/home
- After: 
https://make-a-project--express-website--Webistry-Development.hlx3.page/drafts/rofe/home1?lighthouse=on
> Feat: 'make-a-project' block 

- express/blocks/hero-animation/hero-animation.css
- express/blocks/hero-animation/hero-animation.js
- express/blocks/make-a-project/make-a-project.css
- express/blocks/make-a-project/make-a-project.js
- express/blocks/shared/carousel.css
Continuation of: https://github.com/adobe/express-website/pull/439
XD: https://xd.adobe.com/view/d645e940-92c7-4935-8763-0780e483e6bc-8316/
Test URLs:
- Before: https://mwpw-111363--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home
- After: https://intent-home-3--express-website--webistry-development.hlx.page/drafts/rofe/intent-driven-home1?lighthouse=on
> Intent driven homepage (3rd try)

- express/blocks/floating-button/floating-button.js
- express/scripts/instrument.js
Hotfix no issue provided
Test URLs:
- After: https://floating-analytics--express-website--webistry-development.hlx3.page/express/learn/express-your-brand
> Floating analytics

- express/blocks/make-a-project/make-a-project.css
- express/blocks/make-a-project/make-a-project.js
- express/blocks/shared/carousel.js
- test/unit/blocks/expected/template-list.horizontal.block.html
- Adjust black-round icon sizes
- Fix safari bug reported by sean
- Update failing tests for horizontal templates
Test URLs:
- Before: https://mwpw-111363--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home
- After: https://browser-compatibility--express-website--webistry-development.hlx.page/drafts/rofe/intent-driven-home?lighthouse=on
> Browser compatibility for Intent-driven Homepage

- express/blocks/columns/columns.js
Fix https://github.com/adobe/express-website-issues/issues/347
Test URLs (scroll to the bottom):
- Before: https://main--express-website--adobe.hlx.page/express/create/presentation
- After: https://issue-347--express-website--adobe.hlx.page/express/create/presentation?lighthouse=on
> fix(columns): invert button inside highlight section

- express/blocks/hero-animation/hero-animation.js
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home
- After: https://opt-poster--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home?lighthouse=on
> feat(hero-animation): make poster image optional

- express/blocks/columns/columns.js
- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
Fix https://jira.corp.adobe.com/browse/MWPW-111749
Requirements (desktop only):
1 - if Marquee CTA is visible on page we don't show and floating CTA (see slide-1 in XD)
2 - if Marquee CTA goes below the fold for some reason (screen size or new blade), we show animated Dual floating CTA at the bottom for the page (see slide-2 in XD)
3 - If user is below the fold they see see Floating CTA on the page (see slide-3 in XD)
https://xd.adobe.com/view/277ff9db-032a-45fe-a540-698082462c13-722c/
Test URLs:
- After: https://floating-btn-desktop--express-website--Webistry-Development.hlx.page/express/create/flyer?lighthouse=on
Examples of pages that use the floating button: …
> fix(floating-button): desktop version of floating button

- express/scripts/instrument.js
Fix [MWPW-111731](https://jira.corp.adobe.com/browse/MWPW-111731)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/feature/video/convert/video-to-gif
- After: https://mwpw-111731--express-website--webistry-development.hlx3.page/express/feature/video/convert/video-to-gif
The quick action contextualData is being properly set now.
> feat(quick-actions): add tracking to videoToGif action

- express/blocks/columns/columns.js
- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
- Fix empty section spacing due to floating button block
- Fix https://jira.corp.adobe.com/browse/MWPW-111749
Requirements (desktop only):
1 - if Marquee CTA is visible on page we don't show and floating CTA (see slide-1 in XD)
2 - if Marquee CTA goes below the fold for some reason (screen size or new blade), we show animated Dual floating CTA at the bottom for the page (see slide-2 in XD)
3 - If user is below the fold they see see Floating CTA on the page (see slide-3 in XD)
https://xd.adobe.com/view/277ff9db-032a-45fe-a540-698082462c13-722c/
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/solene/intent-driven-home
- After: https://floating-btn-desktop-2--express-website--Webistry-Development.hlx.page/drafts/solene/intent-driven-home?lighthouse=on
Examples of …
> fix(floating-button): floating button for desktop

- express/blocks/columns/columns.js
- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
Fix https://jira.corp.adobe.com/browse/MWPW-111749
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home
- After: https://mwpw-111749--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home?lighthouse=on
More URLs:
- https://mwpw-111749--express-website--adobe.hlx.page/express/create/logo?lighthouse=on
- https://mwpw-111749--express-website--adobe.hlx.page/de/express/create/logo?lighthouse=on
> [MWPW-111749] floating CTA button on desktop

- tools/fgrep/fgrep.html
- tools/fgrep/fgrep.js
Some enhancements:
- export button for plain text list of paths
- remember and prefill last pattern
- allow autocomplete
> feat: add export button

- express/blocks/quick-action-cards/quick-action-cards.js
- express/styles/styles.css
Fixes a JS error
- Before: https://www.adobe.com/express/feature/quick-actions
- After: https://quick-action-fix--express-website--adobe.hlx.page/express/feature/quick-actions?lighthouse=on
> fix(quick-action-cards): fix js error

- express/scripts/scripts.js
https://remove-optional-chaining--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-65253/clasroom-accounts?lighthouse=on
> chore: remove optional chaining

- express/blocks/blog-posts/blog-posts.js
- express/scripts/blog.js
- express/styles/blog.css
https://blog-tags-category-merge--express-website--adobe.hlx.live/express/learn/blog
vs. 
https://main-category-merge--express-website--adobe.hlx.live/express/learn/blog
> chore: merging category into tags for filtering

- .monitoring/content-check.js
Pricing page has been redesigned, monitor needs to be updated.
> chore: adjust monitor to new pricing page

- express/blocks/content-toggle/content-toggle.css
- express/blocks/content-toggle/content-toggle.js
- express/scripts/instrument.js
Fix MWPW-112525
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/williambsm/content-toggle-demo
- After: https://mwpw-112525--express-website--webistry-development.hlx3.page/drafts/williambsm/content-toggle-demo
This PR contains the Content Toggle block, included with analytics.
> MWPW-112525

- express/blocks/choose-your-path/choose-your-path.css
- express/blocks/choose-your-path/choose-your-path.js
Fix https://jira.corp.adobe.com/browse/MWPW-112524
Test URLs:
https://mwpw-112524--express-website--webistry-development.hlx.page/drafts/williambsm/choose-your-path
> [MWPW-112524] Choose your path block

- express/blocks/content-toggle/content-toggle.css
- express/blocks/content-toggle/content-toggle.js
- express/scripts/instrument.js
Fix https://jira.corp.adobe.com/browse/MWPW-112525
Test URLs:
- https://mwpw-112525--express-website--adobe.hlx.page/drafts/williambsm/content-toggle-demo
> [MWPW-112525] Content Toggle

- express/scripts/instrument.js
Fix MWPW-112424
Test URLs:
- https://mwpw-112424-a--express-website--webistry-development.hlx3.page/express/paths
This branch is meant to add analytics tracking to the slides on the Choose Your Path block.
> feat(choose-your-path): customLink analytics

- express/blocks/quick-action/quick-action.js
Test URLs:
https://quick-action-update--express-website--kushalpandya-js.hlx.page/express/
> Quick action update

- express/blocks/content-toggle/content-toggle.css
- express/blocks/content-toggle/content-toggle.js
Fix https://jira.corp.adobe.com/browse/MWPW-112525
Test URLs:
- https://main--express-website--webistry-development.hlx3.page/drafts/Anuj/education/express
> [MWPW-112524] Content Toggle - Requested changes

- express/blocks/choose-your-path/choose-your-path.css
- express/blocks/choose-your-path/choose-your-path.js
Fix https://jira.corp.adobe.com/browse/MWPW-112524
Test URLs:
https://mwpw-112424-a--express-website--webistry-development.hlx.page/express/paths
This is a small PR made to reflect some small requested changes:
- Open the left sided link on a new tab
- Ensure that the choose your path animation fades out on left side click as well
- Fix the image sizing
I'm aware that the branch has the wrong MWPW name attached to it, that was a typo.
> [MWPW-112524] Small requested changes

- express/scripts/instrument.js
https://alloy-audiences--express-website--adobe.hlx.page/express/feature/image/remove-background
> chore: port audience manager to alloy

- express/blocks/hero-animation/hero-animation.css
https://hero-animation-update--express-website--adobe.hlx.page/express/learn/students/intents
> chore: adjust layout

- express/blocks/make-a-project/make-a-project.css
Fix https://github.com/adobe/express-website-issues/issues/349
Test URLs:
- Before: https://www.adobe.com/express/learn/students
- After: https://issue-349--express-website--adobe.hlx.page/express/learn/students?lighthouse=on
> feat(make-a-project): add spacing if default content

- express/blocks/hero-animation/hero-animation.js
Fix https://github.com/adobe/express-website-issues/issues/351
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/fr/express/
- After: https://issue-351--express-website--adobe.hlx.page/fr/express/?lighthouse=on
> fix(hero-animation): fix poster image quality

- express/blocks/app-store-blade/app-store-blade.css
- express/blocks/app-store-blade/app-store-blade.js
Fix: [adobe](https://jira.corp.adobe.com/browse/MWPW-113696)
Test URLs:
- Before: N/A
- After: https://mwpw-113696--express-website--webistry-development.hlx3.page/drafts/qiyundai/create/generic-app-store-blade?lighthouse=on
> fix(app-store-blade): QA items

- express/blocks/playlist/playlist.css
- express/blocks/playlist/playlist.js
Fix MWPW-112014
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/DOTCOM-68877/express-your-brand
- After: https://mwpw-112014--express-website--webistry-development.hlx.page/drafts/qiyundai/edu-video-block
> fix(playlist): Adapt session title, enable video title hiding, and fix left-align of section title

- express/blocks/app-store-highlight/app-store-highlight.css
- express/blocks/app-store-highlight/app-store-highlight.js
Fix MWPW-113319
Test URLs:
- Before: https://mwpw-113319--express-website--adobe.hlx.page/drafts/qiyundai/create/generic-app-store-highlight?lighthouse=on
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/generic-app-store-highlight?lighthouse=on
> fix(app-store-highlight): re-work structure to allow more flexible CSS rules

- express/blocks/icon-list/icon-list.css
Fix https://github.com/adobe/express-website-issues/issues/352
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-59724/nonprofits
- After: https://issue-352--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-59724/nonprofits?lighthouse=on
> fix(icon-list): spacing issues

- express/blocks/app-store-blade/app-store-blade.js
- express/scripts/scripts.js
Fix MWPW-113696
Test URL:
https://mwpw-113696--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
> fix(app-store-blade): enable block to auto render without a placeholder

- express/blocks/app-store-highlight/app-store-highlight.css
- express/blocks/app-store-highlight/app-store-highlight.js
- express/scripts/scripts.js
Fix MWPW-113319
Test URL:
https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
> fix(app-store-highlight): enable buildAutoBlocks + screenshots styling fix

- express/blocks/app-store-highlight/app-store-highlight.css
- express/blocks/app-store-highlight/app-store-highlight.js
- express/scripts/scripts.js
Fix MWPW-113319
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/brochure?lighthouse=on
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
> fix(app-store-highlight): hotfix

- express/blocks/playlist/playlist.js
- express/scripts/instrument.js
Fix MWPW-112014: analytics missing
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/edu-video-block?lighthouse=on
- After: https://mwpw-112014--express-website--webistry-development.hlx.page/drafts/qiyundai/edu-video-block?lighthouse=on
> fix(playlist): changing interactive element tag type to facilitate analytics

- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
- karma.config.js
Feat Mwpw 115165
Test URLs:
https://mwpw-115165--express-website--webistry-development.hlx.page/drafts/qiyundai/templates?lighthouse=on
https://mwpw-115165--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates?lighthouse=on
> Mwpw 115165: free-in-app badge

- express/blocks/template-list/template-list.css
Fix MWPW-113213
Test URLs:
https://mwpw-113213--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-api-powered
> feat(api-powered-grid): fix safari layout issue

- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
- karma.config.js
- test/unit/blocks/expected/template-list.horizontal.block.html
- test/unit/blocks/expected/template-list.linkwithtext.block.html
- test/unit/blocks/expected/template-list.sixcols.block.html
- test/unit/blocks/expected/template-list.title.block.html
- test/unit/blocks/expected/template-list.video.block.html
- test/unit/mocks/express/placeholders.json
Fix https://jira.corp.adobe.com/browse/MWPW-115165
Test URLs:
- https://mwpw-115165--express-website--adobe.hlx.page/drafts/qiyundai/templates?lighthouse=on
- https://mwpw-115165--express-website--adobe.hlx.page/drafts/qiyundai/templates/flyer-templates?lighthouse=on
> MWPW-115165

- express/blocks/ratings/ratings.css
- express/blocks/ratings/ratings.js
Fixes issue: 'The votes should not appear if the ratings have not been received from the API'
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo/random
- After: https://hide-0-votes--express-website--webistry-development.hlx.page/express/create/logo/random
> fix(ratings): hide votes if the api didn't work

- express/blocks/columns/columns.css
- express/scripts/scripts.js
Fix mwpw-113319
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
> fix(app-store-highlight): fixing side-effects from splitting sections

- express/blocks/template-list/template-list.js
Fix MWPW-113213
Test URLs:
- Before: https://main--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-api-powered?lighthouse=on
- After: https://mwpw-113213--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-api-powered?lighthouse=on
- Missing rows: https://mwpw-113213--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-api-powered-miss-rows?lighthouse=on
- Missing type value: https://mwpw-113213--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-api-powered-miss-type-value?lighthouse=on
> feat(api-powered-grid): adding authoring rows for more query params

- express/blocks/choose-your-path/choose-your-path.js
Fix https://github.com/adobe/express-website-issues/issues/353
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/paths?lighthouse=on
- After: https://issue-353--express-website--adobe.hlx.page/de/express/paths?lighthouse=on
> fix(choose-your-path): localization

- express/blocks/hero-animation/hero-animation.js
Fix https://github.com/adobe/express-website-issues/issues/354
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/nonprofits
- After: https://issue-354--express-website--adobe.hlx.page/express/nonprofits?lighthouse=on
> feat(hero-animation): auto-play video on hash

- express/blocks/app-store-highlight/app-store-highlight.js
Fix mwpw-113319
Test URLs:
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/express/create/flyer
> fix(app-store-highlight): refactor video url

- express/blocks/ratings/ratings.js
Test URLs:
- Before: https://www.adobe.com/express/create/logo/random
- After: https://ratings-fix--express-website--adobe.hlx.page/express/create/logo/random?action-used=true&lighthouse=on
> fix(ratings): fix json retrieval from fetch response

- express/blocks/app-store-blade/app-store-blade.js
- express/blocks/app-store-highlight/app-store-highlight.js
Fix dotcom-69214
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo/random
- After: https://dotcom-69214--express-website--webistry-development.hlx.page/express/create/logo/random
> fix(app-store-blocks): fail silently if can't find block to follow

- express/blocks/playlist/playlist.js
- express/blocks/shared/video.js
No JIRA issue ID provided as it is a hotfix.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/learn/express-your-brand
- After: https://mwpw-112014-heartbeat--express-website--webistry-development.hlx.page/express/learn/express-your-brand
Someone with access to heartbeat analytics will need to test this.
> feat(playlist): heartbeat tracking

- express/blocks/download-cards/download-cards.css
- express/blocks/sticky-footer/sticky-footer.js
Fixes:
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/maxed/test
- After: https://mwpw-114266--express-website--adobe.hlx.page/drafts/maxed/test
> fix: safari bugs

- express/blocks/download-screens/download-screens.css
- express/blocks/hero-3d/hero-3d.css
- express/blocks/hero-3d/hero-3d.js
fixes: 
Test URLs:
Before: https://main--express-website--adobe.hlx.page/drafts/maxed/test
After: https://mwpw-114266--express-website--adobe.hlx.page/drafts/maxed/test
> fix: style tweaks

- express/blocks/hero-animation/hero-animation.css
- express/blocks/hero-animation/hero-animation.js
Fix <https://jira.corp.adobe.com/browse/MWPW-116370>
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/
- After: https://mwpw-116370--express-website--adobe.hlx.page/de/express/?lighthouse=on
Regression check:
- After: https://mwpw-116370--express-website--adobe.hlx.page/express/?lighthouse=on
> fix(hero-animation): stack free plan widget for long CTAs

- express/scripts/scripts.js
Fix https://jira.corp.adobe.com/browse/MWPW-116263
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/project-x-test
- After: https://mwpw-116263--express-website--adobe.hlx.page/express/project-x-test?lighhouse=on
> feat: suppress gnav via metadata

- express/blocks/choose-your-path/choose-your-path.js
Fix [MWPW-116348](https://jira.corp.adobe.com/browse/MWPW-116348)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/paths
- After: https://mwpw-116348--express-website--webistry-development.hlx.page/drafts/williambsm/mwpw-116348?parameter=test
- Removing the new tab behavior of link slides.
- Passing along url parameters to link slides.
- Removing the fade out effect of non-link slides.
> [MWPW-116348] Choose your path behavior changes

- express/styles/blog.css
Buttons affected by global styling for P elements!
Test URLs:
- Before: https://www.adobe.com/express/learn/blog/google-classroom-add-on
- After: https://fix-buttons--express-website--adobe.hlx.page/express/learn/blog/google-classroom-add-on
> fix(express/styles/blog.css): fix

- express/blocks/puf/puf.css
- express/blocks/puf/puf.js
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/pricing?country=gb
- After: https://puf-vat--express-website--adobe.hlx.page/express/pricing?country=gb&lighthouse=on
> feat(puf): show vat info when available

- express/blocks/template-list/template-list.js
Fix https://jira.corp.adobe.com/browse/MWPW-115944
Test URLs
https://mwpw-115944--express-website--webistry-development.hlx.page/drafts/qiyundai/templates/flyer-templates-with-relevant-rows
> feat(relevant-rows): expand ratio control to horizontal tmplt list

- express/blocks/template-list/template-list.css
Fix MWPW-115944
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/banner
- After: https://template-list-width-fix--express-website--webistry-development.hlx.page/express/create/banner
> fix(relevant-rows): limit max-width of template list card

- express/scripts/scripts.js
Fix Section padding-top in general
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/banner
- After: https://padding-normalizer--express-website--webistry-development.hlx.page/express/create/banner
> fix(relevant-rows): added padding normalizer

- express/blocks/ratings/ratings.css
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo/random
- After: https://ratings-countdown-styling--express-website--adobe.hlx.page/express/create/logo/random?lighthouse=on
> fix(ratings): countdown animation has gray bg

- express/blocks/split-action/split-action.css
- express/blocks/split-action/split-action.js
- express/scripts/instrument.js
[Feat(split-action): MWPW-115946](https://jira.corp.adobe.com/browse/MWPW-115946)
Test URLs:
https://ccx0068--express-website--webistry-development.hlx.page/drafts/qiyundai/feature/image/remove-background
> Feat(split-action): MWPW-115946

- express/blocks/columns/columns.css
- express/blocks/floating-button/floating-button.css
- express/blocks/hero-animation/hero-animation.css
- express/styles/styles.css
Fix https://github.com/adobe/express-website-issues/issues/355
Test URLs (check all breakpoints for regressions):
Homepage (en):
- After: https://issue-355--express-website--adobe.hlx.page/express/?lighthouse=on
Homepage (de):
- Before: https://main--express-website--adobe.hlx.page/de/express/
- After: https://issue-355--express-website--adobe.hlx.page/de/express/?lighthouse=on
Homepage (kr):
- Before: https://main--express-website--adobe.hlx.page/kr/express/
- After: https://issue-355--express-website--adobe.hlx.page/kr/express …
> fix(free-plan-widget): mobile issues

- express/scripts/gnav.js
- express/scripts/scripts.js
Fix [MWPW-116972](https://jira.corp.adobe.com/browse/MWPW-116972)
Test URLs:
- [No geocheck on German site](https://geocheck-redirect--express-website--adobe.hlx.page/de/express/)
- [Geocheck on main site](https://geocheck-redirect--express-website--adobe.hlx.page/express/?geocheck=on)
- [Geocheck forced on Japanese site](https://geocheck-redirect--express-website--adobe.hlx.page/jp/express/create?geocheck=force)
> [MWPW-116972] Client-side geocheck and redirect based on FEDS

- express/scripts/gnav.js
- express/scripts/scripts.js
Fix [MWPW-116972](https://jira.corp.adobe.com/browse/MWPW-116972)
Test URLs:
- [No geocheck on German site](https://geocheck-fix--express-website--adobe.hlx.page/de/express/)
- [Geocheck on main site](https://geocheck-fix--express-website--adobe.hlx.page/express/?geocheck=on)
- [Geocheck forced on Japanese site](https://geocheck-fix--express-website--adobe.hlx.page/jp/express/create?geocheck=force)
> Geocheck fix

- express/scripts/instrument.js
- fstab.yaml
Fix [MWPW-115946](https://jira.corp.adobe.com/browse/MWPW-115946)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/feature/image/remove-background
- After: https://ccx0068--express-website--webistry-development.hlx.page/drafts/qiyundai/feature/image/remove-background
> fix(split-action): rename tracking events

- express/blocks/template-list/template-list.js
Fix template-list regression
Test URLs:
- Before: https://www.adobe.com/nl/express/create/banner
- After: https://hotfix-templatelist--express-website--webistry-development.hlx.page/nl/express/create/banner
> fix(template-list): find matching options in blueprint blocks

- express/blocks/sticky-footer/sticky-footer.css
Fix sticky-footer
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/design-app
- After: https://hotfix-stickyfooter--express-website--webistry-development.hlx.page/de/express/design-app
> fix(sticky-footer): localized text layout fix

- express/blocks/app-store-highlight/app-store-highlight.js
- express/blocks/collapsible-card/collapsible-card.css
- express/scripts/scripts.js
Fix MWPW-115944
Test URLs:
Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer
After: https://relevant-rows-fix--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer
> fix(relevant-rows): added condition for no splitting

- express/blocks/fragment/fragment.js
Update fragment block to the latest version from https://www.hlx.live/developer/block-collection/fragment
Also fixes this issue on mobile:
Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/create
After: https://fragment-update--express-website--adobe.hlx.page/drafts/Anuj/create?lighthouse=on
> feat(fragment): update to latest version

- express/scripts/templates.js
Untested changes due to the inability to publish changes to the metadata.xslx file.
> [MWPW-113214] Adding locale and format placeholder support

- express/blocks/faq/faq.css
- express/blocks/faq/faq.js
- test/unit/blocks/expected/faq.block.html
Feat [MWPW-116568](https://jira.corp.adobe.com/browse/MWPW-116568) & Fix [MWPW-116215](https://jira.corp.adobe.com/browse/MWPW-116215)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo
- After: https://mwpw-116568-116215--express-website--webistry-development.hlx3.page/express/create/logo
> feat(faq): add schema, add subheading formatting

- express/scripts/templates.js
Before: https://mwpw-113214--express-website--adobe.hlx.page/express/templates/flyer
After : https://mwpw-113214--express-website--webistry-development.hlx.page/express/templates/flyer
> fix(seo-templates): Remove link lists if empty

- express/blocks/icon-list/icon-list.css
Fix https://github.com/adobe/express-website-issues/issues/356
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/nonprofits
- After: https://issue-356--express-website--adobe.hlx.page/drafts/Anuj/nonprofits?lighthouse=on
> fix(icon-list): add container bottom margin

- express/blocks/columns/columns.js
- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
- express/styles/styles.css
Fix Floating Button
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
- After: https://floating-button-fix--express-website--webistry-development.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
> fix(floating-button): inheriting data-audience

- express/blocks/columns/columns.js
Fix floating button bug
Test URLs:
- After: https://floating-button-fix--express-website--webistry-development.hlx.page/express/create/flyer
> fix(floating-button): ignore audience if only one column exists

- express/blocks/columns/columns.js
Fix floating button regression
Test URLs:
- Before: 
- - https://main--express-website--adobe.hlx.page/express/create/flyer
- - https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
- After:
- - https://floating-button-fix--express-website--webistry-development.hlx.page/express/create/flyer
- - https://floating-button-fix--express-website--webistry-development.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
> fix(floating-button): better mechanism of checking for columns dataset

- tools/preview/preview.js
URL for testing:
- https://experiments-ui-data--express-website--adobe.hlx.page/drafts/lars/explore
Collapsed:
Expanded:
Fully loaded:
> feat(experiments): show more data in experiment tool overlay

- express/blocks/columns/columns.js
- express/blocks/floating-button/floating-button.js
Test URLs:
Before:
https://main--express-website--adobe.hlx.page/express/create/flyer
https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
After:
https://floating-button-fix--express-website--webistry-development.hlx.page/express/create/flyer
https://floating-button-fix--express-website--webistry-development.hlx.page/drafts/ernest_sallee/DOTCOM-73636/content-scheduler
> fix(floating-button): permanent fix for floating button data-audience issue

- tools/preview/preview.js
Test URL:
https://rum-fix--express-website--adobe.hlx.page/drafts/lars/explore?experiment=ccx0076
> Fix: use correct starting assumptions for determintation of winner

- express/blocks/puf/puf.js
Fix https://jira.corp.adobe.com/browse/MWPW-118438
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/pricing
- After: https://mwpw-118438--express-website--webistry-development.hlx.page/express/pricing?lighthouse=on
Making the free plan the default plan to show up on load.
> feat(puf): Free plan selected by default

- express/blocks/plans-comparison/plans-comparison.css
- express/blocks/plans-comparison/plans-comparison.js
- express/scripts/scripts.js
split plans-comparison blade into its own section
Fix MWPW-117393
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/discover/templates
- After: https://fix-mwpw-117393--express-website--webistry-development.hlx.page/drafts/qiyundai/discover/templates?lighthouse=on
> fix: (MWPW-117393)

- express/blocks/floating-button/floating-button.css
Fix mwpw-118367
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/social-media-graphic
- After: 
-- https://fix-mwpw-118367--express-website--webistry-development.hlx.page/express/create/social-media-graphic?lighthouse=on
-- https://fix-mwpw-118367--express-website--webistry-development.hlx.page/express/create/flyer?lighthouse=on
> fix(MFB): add padding for long text

- tools/sidekick/config.json
Sidekick mv3 config schema: https://github.com/adobe/helix-sidekick-extension/blob/mv3/docs/config.schema.json
> chore(sidekick): update config to latest schema

- express/scripts/gnav.js
Fix https://jira.corp.adobe.com/browse/MWPW-118283
Test URL (chatbot can only be tested in production unfortunately):
- https://gnav-cfg--express-website--adobe.hlx.page/drafts/rofe/home?lighthouse=on
> MWPW-118283 - Jarvis Chat Bot

- express/scripts/gnav.js
Fix https://jira.corp.adobe.com/browse/MWPW-119626
Test URLs:
- After: https://mwpw-119626--express-website--adobe.hlx.page/express/?lighthouse=on
> feat: upgrade to mega nav

- express/scripts/scripts.js
- express/styles/styles.css
The hero section stays invisible if audience is defined in section metadata.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/dotcom-74358/schedule
- After: https://hero-section-issue--express-website--adobe.hlx.page/drafts/Anuj/dotcom-74358/schedule?lighthouse=on
> chore: hero section issue

- express/blocks/app-store-highlight/app-store-highlight.css
- express/blocks/app-store-highlight/app-store-highlight.js
- express/blocks/download-screens/download-screens.css
- express/blocks/download-screens/download-screens.js
Fix scroll animation
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer
- Before: https://main--express-website--adobe.hlx.page/drafts/maxed/test
- After: https://ease-scroll-animation--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer?lighthouse=on
- After: https://ease-scroll-animation--express-website--webistry-development.hlx.page/drafts/maxed/test?lighthouse=on
> Ease scroll animation

- express/blocks/browse-by-category/browse-by-category.css
- express/blocks/browse-by-category/browse-by-category.js
Fix browse by category block
Removed hard coded language.
More robust authoring experience
Better layout for long category names
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/yge/en/Tests/templates-holiday-test?lighthouse=on
- After: https://fix-browse-bugs--express-website--webistry-development.hlx.page/drafts/yge/en/Tests/templates-holiday-test?lighthouse=on
> fix(browse-by-category): multiple improvements

- express/blocks/hero-animation/hero-animation.css
- express/styles/styles.css
Test URLs:
- After: https://header-fix--express-website--adobe.hlx.page/express/?lighthouse=on
> Header fix

- express/blocks/quick-action-hub/quick-action-hub.js
No test urls needed. I just fixed an extra white space in the code to prevent the lint checker from bringing it up on all PRs.
> fix(quick-action-hub): linting error

- express/blocks/plans-comparison/plans-comparison.css
- express/blocks/plans-comparison/plans-comparison.js
fix(plans-comparison): long text clipping bug fix (no ticket)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/tw/express/fragments/plans-comparison
- After: https://fix-plans-comparison--express-website--webistry-development.hlx.page/tw/express/fragments/plans-comparison?lighthouse=on
> fix(plans-comparison): long text clipping bug fix

- express/blocks/template-list/template-list.js
Fix [MWPW-120748](https://jira.corp.adobe.com/browse/MWPW-120748) [desktop/mobile] Template SEO pages- Grammar issues
Test URLs:
- https://mwpw-120748--express-website--webistry-development.hlx.page/express/templates/flyer/christmas?lighthouse=on
- https://mwpw-120748--express-website--webistry-development.hlx.page/fr/express/templates/flyer/christmas?lighthouse=on
- https://mwpw-120748--express-website--webistry-development.hlx.page/fr/express/templates/infographic/timeline?lighthouse=on
- https://mwpw-120748--express-website--webistry-development.hlx.page/it/express/templates/business-card/art?lighthouse=on
- https://mwpw-120748--express-website--webistry-development.hlx.page/tw/express/templates/banner/gaming?lighthouse=on
> Mwpw 120748 [desktop/mobile] Template SEO pages- Grammar issues

- express/scripts/scripts.js
Fix https://jira.corp.adobe.com/browse/MWPW-121202
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/card/christmas/funny
- After: https://mwpw-121202--express-website--adobe.hlx.page/express/create/card/christmas/funny?lighthouse=on
> chore: disable brand header if mega nav

- .eslintignore
- express/blocks/hero-3d/hero-3d.css
- express/blocks/hero-animation/hero-animation.css
- express/blocks/hero-image/hero-image.css
- express/blocks/plans-comparison/plans-comparison.css
- express/blocks/plans-comparison/plans-comparison.js
- express/blocks/template-list/template-list.js
- express/scripts/scripts.js
- express/scripts/ued/ued-0.2.0.js
- express/styles/styles.css
Fix SITES-8905
Test URLs:
- Before: https://main--express-website--adobe.hlx.live/express/create/flyer?lighthouse=on
- After: https://ued-integration--express-website--adobe.hlx.live/express/create/flyer?lighthouse=on
> Ued integration

- express/styles/styles.css
Fix https://jira.corp.adobe.com/browse/MWPW-121663
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/video/animation/instagram
- After: https://desktop-no-hyphens--express-website--adobe.hlx.page/express/create/video/animation/instagram?lighthouse=on
> chore: no hyphenation on desktop

- express/blocks/fullscreen-marquee/fullscreen-marquee.js
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer3
- After: https://mwpw-119277--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer3?lighthouse=on
> chore: use relative image urls

- express/blocks/fullscreen-marquee/fullscreen-marquee.js
Fix [mwpw 119277](https://jira.corp.adobe.com/browse/MWPW-119277)
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/create/flyer
After: https://mwpw-119277--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer3?lighthouse=on
> feat(new-marquee): add additional CTA on hover

- express/blocks/link-list/link-list.css
- express/blocks/template-list/template-list.js
- express/scripts/scripts.js
- express/styles/styles.css
Fix [MWPW-121961](https://jira.corp.adobe.com/browse/MWPW-121961): Template SEO pages issue
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer
- After: https://mwpw-121961--express-website--webistry-development.hlx.page/express/templates/flyer?lighthouse=on
> fix(template-seo): Template SEO pages issue

- express/blocks/blog-posts/blog-posts.css
- express/styles/blog.css
Test URLs:
- Blog homepage:
- Before: https://www.adobe.com/jp/express/learn/blog
- After: https://jp-font-blog--express-website--adobe.hlx.live/jp/express/learn/blog?lighthouse=on
- Blog post:
- Before: https://www.adobe.com/jp/express/learn/blog/introducing-creative-cloud-express
- After: https://jp-font-blog--express-website--adobe.hlx.live/jp/express/learn/blog/introducing-creative-cloud-express?lighthouse=on
> Japanese blog: switch to sans-serif font

- test/unit/blocks/expected/template-list.horizontal.block.html
- test/unit/blocks/expected/template-list.linkwithtext.block.html
- test/unit/blocks/expected/template-list.sixcols.block.html
- test/unit/blocks/expected/template-list.title.block.html
- test/unit/blocks/expected/template-list.video.block.html
https://fix-template-list-tests--express-website--adobe.hlx.page/express/create/flyer?lighthouse=on
> chore: fix tests

- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
No ticket. Fix Spreadsheet Based Multifunction Button where the lottie arrow code querySelector dodges the blocks it looks for.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/agenda/meeting
- After: https://mwpw-119933-fix--express-website--webistry-development.hlx.page/express/create/agenda/meeting?lighthouse=on
> [MWPW-119933] Fix: Multifunction Button hides Lottie Arrow Correctly

- express/scripts/scripts.js
Fix MWPW-119933. No Ticket.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/es/express/create/badge?lighthouse=on
- After: https://fix-mwpw-119933--express-website--webistry-development.hlx.page/es/express/create/badge?lighthouse=on
> [MWPW-119933] - Fix Localized Sheet URL for Spreadsheet Powered MFB

- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
Fix Localized Multifunction Button, No ticket.
Test URLs:
Before: 
- https://main--express-website--adobe.hlx.page/jp/express/create/resume
- Before: https://main--express-website--adobe.hlx.page/es/express/create/announcement/baby-girl
After: 
- https://mfb-loc-fix--express-website--webistry-development.hlx.page/jp/express/create/resume?lighthouse=on
- https://mfb-loc-fix--express-website--webistry-development.hlx.page/es/express/create/announcement/baby-girl?lighthouse=on
> fix(mfb-loc-fix): fix localization RTP ui issues

- express/scripts/templates.js
Fix **NO JIRA ISSUE**
Fixed the link list button at the bottom of the page.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/
- After: https://template-seo-fix--express-website--webistry-development.hlx.page/express/templates/?lighthouse=on
> fix(template-seo): replaceAll to also replace button title

- express/styles/styles.css
Fix mwpw-121561, hotfix without ticket
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/fr/express/pricing
- After: https://mwpw-121561--express-website--webistry-development.hlx.page/fr/express/pricing?lighthouse=on
> fix(free-plan-bullet): apply new bullet design only inside a button container

- express/blocks/plans-comparison/plans-comparison.js
- express/scripts/scripts.js
removed double locale assignment.
added guard condition to highlight banner.
Hotfix. No ticket.
Test URLs:
Before: 
- https://main--express-website--adobe.hlx.page/express/create/logo
- https://main--express-website--adobe.hlx.page/de/express/create/logo
- https://main--express-website--adobe.hlx.page/fr/express/create/logo
- https://main--express-website--adobe.hlx.page/es/express/create/logo
After: 
- https://plans-comparison-fix--express-website--webistry-development.hlx.page/express/create/logo?lighthouse=on
- https://plans-comparison-fix--express-website--webistry-development.hlx.page/de/express/create/logo?lighthouse=on
- https://plans-comparison-fix--express-website--webistry-development.hlx.page/fr/express/create/logo?lighthouse=on
- …
> fix(localized-plans-comparison): localized url fix

- express/scripts/scripts.js
- express/styles/styles.css
No ticket. Fix free-plan-widget centering issue.
Test URLs:
Before: 
- https://main--express-website--adobe.hlx.page/express/
- https://main--express-website--adobe.hlx.page/express/create/logo
- https://main--express-website--adobe.hlx.page/express/create/flyer
- https://main--express-website--adobe.hlx.page/fr/express/create/instagram-story
- https://main--express-website--adobe.hlx.page/express/feature/image/remove-background
After: 
- https://free-plan-center--express-website--webistry-development.hlx.page/express/?lighthouse=on
- https://free-plan-center--express-website--webistry-development.hlx.page/express/create/logo?lighthouse=on
- https://free-plan-center--express-website--webistry-development.hlx.page/express/create/flyer?lighthouse=on
- …
> [No Ticket] - Fix Free Plan Widget Centering Issue

- express/styles/styles.css
Hotfix columns block CTA on mobile
Test URLs:
- After: https://legacy-cta-fix--express-website--webistry-development.hlx.page/express/feature/image/remove-background?lighthouse=on
> [No Ticket] fix(free-plan-widget): Avoid conflict with mobile same as floating CTA special treatment

- express/styles/styles.css
Test URLs (see last section):
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/avatar
- After: https://long-form-section--express-website--adobe.hlx.page/drafts/rofe/avatar?lighthouse=on
> feat: long form section style

- express/styles/styles.css
Follow-up PR to harmonize heading sizes in long form sections.
Fix <jira-issue-id> @abhinch?
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/avatar
- After: https://long-form-section--express-website--adobe.hlx.page/drafts/rofe/avatar?lighthouse=on
> Long form section

- express/blocks/content-toggle/content-toggle.css
- express/blocks/content-toggle/content-toggle.js
Fix: https://jira.corp.adobe.com/browse/MWPW-122824
Test URLs:
- Before: https://main--express-website--webistry-development.hlx.page/drafts/casey/content-toggle/pricing-toggle-only
- After: https://m-122824-2--express-website--webistry-development.hlx.page/drafts/casey/content-toggle/pricing-toggle-only?lighthouse=on
Implemented content toggle for the pricing page, including a dark variant. Additionally, enabled the ability to add tags to each toggle using square brackets at the end of the toggle text.
> [MWPW-122824-2] Content-Toggle

- express/blocks/link-list/link-list.css
- express/blocks/link-list/link-list.js
Fix https://jira.corp.adobe.com/browse/MWPW-122824
Test URLs (for previous works involving the content toggle block):
Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/pricing/shaded-linklist
After: https://mwpw-122824-3--express-website--webistry-development.hlx.page/drafts/qiyundai/pricing/shaded-linklist?lighthouse=on
> [MWPW-122824-3] Shaded & Centered variants of Linklist

- express/blocks/app-banner/app-banner.js
- express/blocks/collapsible-card/collapsible-card.js
- express/blocks/shared/carousel.js
Fix [MWPW-125709](https://jira.corp.adobe.com/browse/MWPW-125709)
The solutions for all SEO issues are work in progress. This PR in particular is to address the collapsible-card block auto collapsing contributing to CLS as well as a quick fix for an issue related to the app-banner spotted during the process.
On the preview link, you will notice a broken relevant rows section. It's unrelated to the fix on this branch. The fix for that is being worked on separately.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/brochure
- After: …
> [MWPW-125709] SEO Tech Issue Fixes - Stage 1

- express/blocks/fragment/fragment.js
- express/scripts/scripts.js
Fix https://jira.corp.adobe.com/browse/MWPW-119939
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/create/flyer
After: https://relevant-row-fixes--express-website--webistry-development.hlx.page/express/create/flyer?lighthouse=on
There are a few things to note here:
1. I made the buildAutoBlocks function async, and I did not notice any page breaking bugs, but we should be careful.
2. I moved the getHelixEnv() function around to prevent a linting error.
3. I added a spreadsheet check to only load the blocks if there is a match, this may impact performance on /create …
> [MWPW-119939] Fixing Relevant Rows production breaking bug

- express/styles/styles.css
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/avatar
- After: https://long-form-spacing--express-website--adobe.hlx.page/drafts/rofe/avatar?lighthouse=on
> chore: long form bottom spacing

- express/scripts/scripts.js
- express/styles/styles.css
Fix [MWPW-127108](https://jira.corp.adobe.com/browse/MWPW-127108)
Test URLs:
- After: https://mwpw-127108--express-website--webistry-development.hlx.page/express/feature/image/remove-background?lighthouse=on
https://mwpw-127108--express-website--webistry-development.hlx.page/express/create/flyer?lighthouse=on
https://mwpw-127108--express-website--webistry-development.hlx.page/express/create/business-card?lighthouse=on
> [MWPW-127108] Remove Free Plan Highlight Scrolling Interaction

- express/scripts/gnav.js
Quick test for stage environment. No code changes.
> test for stage ims

- express/scripts/gnav.js
This change is fixing the IMS login for stage.adobe.com/express. And is meant only for the stage branch (merging this change in the main branch will break the log in on production).
> Setting the IMS environment to stage for the stage branch

- express/blocks/hero-animation/hero-animation.css
No ticket. Fixing authoring blocker on a monetization page.
Fix Hero Animation
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/business?lighthouse=on
- After: https://hero-animation-fix--express-website--webistry-development.hlx.page/drafts/Anuj/business?lighthouse=on
> fix(hero-animation): centering animation video

- express/blocks/ratings/ratings.css
No ticket
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo/random
- After: https://ratings-css-fix--express-website--webistry-development.hlx.page/express/create/logo/random?lighthouse=on
> fix(ratings): Adding .block combo class to prevent creeping

- 404.html
Fix AEXG-3024
Test URLs:
- Before: 
https://main--express-website--adobe.hlx.live/express/edu?locale=jcy-GB
https://main--express-website--adobe.hlx.live/express/edu?locale=da-DK
https://main--express-website--adobe.hlx.live/express/edu?locale=de-DE
https://main--express-website--adobe.hlx.live/express/edu?locale=en-US
https://main--express-website--adobe.hlx.live/express/edu?locale=es-ES
https://main--express-website--adobe.hlx.live/express/edu?locale=fi-FI
https://main--express-website--adobe.hlx.live/express/edu?locale=fr-FR
https://main--express-website--adobe.hlx.live/express/edu?locale=it-IT
https://main--express-website--adobe.hlx.live/express/edu?locale=ja-JP
https://main--express-website--adobe.hlx.live/express/edu?locale=ko-KR …
> fix: added missing trailing slash for edu redirects

- express/blocks/app-store-blade/app-store-blade.css
- express/blocks/app-store-blade/app-store-blade.js
Fix [MWPW-127569](https://jira.corp.adobe.com/browse/MWPW-127569)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/advertisement
- After: https://mwpw-127569--express-website--webistry-development.hlx.page/express/create/advertisement?lighthouse=on
> [MWPW-127569] Update <a href> to not be a link on App Store Blade

- express/experiments/ccx0027/blocks/quick-action1/quick-action.js
- express/experiments/ccx0027/blocks/quick-action2/quick-action.js
adding title to the close button
Fix [SITES-11254](https://jira.corp.adobe.com/browse/SITES-11254)
Test URLs:
https://frictionless-restart-action-title--express-website--ravkiran.hlx.page/express/experiments/ccx0027/quick-action?experiment=ccx0027%2Fchallenger-2
> fix: adding title to close button

- express/experiments/ccx0027/blocks/quick-action1/quick-action.css
- express/experiments/ccx0027/blocks/quick-action2/quick-action.css
Fixing alignment issues for the media container and utility
Fix [SITES-11254](https://jira.corp.adobe.com/browse/SITES-11254)
Test URLs:
https://utility-alignment--express-website--ravkiran.hlx.live/express/feature/image/remove-background?experiment=ccx0027%2Fchallenger-1
> fix: utility alignment issues

- express/blocks/quick-action/shared.js
Test URLs:
https://transient-token-fix--express-website--ravkiran.hlx.page/express/feature/image/remove-background?experiment=ccx0027%2Fchallenger-2
> fix: transientToken request parameter shouldn't be added when empty

- helix-sitemap.yaml
https://sitemap-seo-templates--express-website--adobe.hlx.page/express/?lighthouse=on
> chore: sitemap for seo templates

- express/scripts/gnav.js
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/pricing
- After: https://geopicker-redirects--express-website--adobe.hlx.page/express/pricing
> refactor: geopicker redirection

- express/sitemap.xml
> chore: update sitemap index

- express/scripts/templates.js
Fix No Ticket
**Task description:**
Quick fix for Template SEO Pages not redirecting
**Test URLs:**
Before: https://main--express-website--adobe.hlx.page/express/templates/tag
After: https://seo-redirect--express-website--webistry-development.hlx.page/express/templates/tag?lighthouse=on
> [NO-TICKET]: Quick fix for Template SEO Pages redirecting

- express/blocks/feature-grid-desktop/feature-grid-desktop.js
- express/blocks/intent-toggle-desktop/intent-toggle-desktop.css
- express/blocks/intent-toggle-desktop/intent-toggle-desktop.js
- express/scripts/preference-store.js
Feat homepage-v3
Refactor PreferenceStore
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/jinglhua/feature-grid-desktop?lighthouse=on
- After: https://homepage-v3--express-website--adobe.hlx.page/drafts/jinglhua/feature-grid-desktop?lighthouse=on
> feat(feature-grid-desktop): preferenceStore refactor

- express/blocks/feature-grid-desktop/feature-grid-desktop.js
Test URLs:
- Before: https://homepage-v3--express-website--adobe.hlx.page/drafts/jinglhua/feature-grid-desktop
- After: https://feature-grid-animation--express-website--adobe.hlx.page/drafts/jinglhua/feature-grid-desktop
> feat(feature-grid): rm replay

- express/blocks/shared/floating-cta.js
- express/blocks/split-action/split-action.css
- express/blocks/split-action/split-action.js
Fix [mwpw-129542](https://jira.corp.adobe.com/browse/MWPW-129542)
- Refactored to remove $
- Fix missing block bug caused by missing floating-cta
to test, click on any cta on the after page and see the split-action loaded.
**Test URLs:**
- After: https://split-action-fix--express-website--webistry-development.hlx.page/express/feature/image/remove-background
> [MWPW-129542] Split Action: Missing block fix

- express/blocks/circle-list-desktop/circle-list-desktop.css
- express/blocks/circle-list-desktop/circle-list-desktop.js
Fix: https://jira.corp.adobe.com/browse/MWPW-123032
Test URLs:
- Before: https://homepage-v3--express-website--adobe.hlx.page/drafts/qiyundai/intent-toggle/draft
- After: https://circle-list-desktop-2--express-website--webistry-development.hlx.page/drafts/qiyundai/intent-toggle/draft?lighthouse=on
Implemented small viewport circle-list, fixed lottie refresh issue, text highlighting among other visual changes.
> Circle list desktop 2

- express/scripts/scripts.js
Fix [SITES-11885](https://jira.corp.adobe.com/browse/SITES-11885)
Test URLs:
https://sites-11885_contentsquare--express-website--adobe.hlx.page/express/experiments/ccx0027/quick-action?experiment=ccx0027%2Fchallenger-1
> SITES-11885 - Integrate Content Square with Franklin Experimentation

- express/scripts/fonts.js
- express/scripts/instrument.js
- express/scripts/scripts.js
- express/styles/styles.css
- test/unit/scripts/fonts.test.js
Fix [MWPW-129166](https://jira.corp.adobe.com/browse/MWPW-129166)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/jp/express/?lighthouse=on
- After: https://japanese-font--express-website--adobe.hlx.page/jp/express/?lighthouse=on
> MWPW-129166 fix font issue japanese

- express/blocks/template-list/template-list.css
- express/scripts/templates.js
Fix [MWPW-119603](https://jira.corp.adobe.com/browse/MWPW-119603)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/br/express/templates/flyer?lighthouse=on
- After: https://ckg-locales-release--express-website--webistry-development.hlx.page/br/express/templates/flyer?lighthouse=on
> [MWPW-119603] CKG Pill global release: remove constraint on locales

- express/scripts/api-v3-controller.js
- express/scripts/templates.js
Hotfix CKG release on locale:
- linklist qa sheet location was invalid for prod
- redirect was causing issue for searching
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/br/express/templates/flyer?lighthouse=on
- After: https://ckg-release-hotfix--express-website--webistry-development.hlx.page/br/express/templates/flyer?lighthouse=on
> [HOTFIX] CKG Locales Release: fix sheet location issue, remove broken redirects

- express/blocks/template-list/template-list.js
- express/scripts/templates.js
**Description**:
Hotfix CKG release on locale:
- if locale missing from linklist qa sheet, don't use the cell value
- fire ckg api call to the correct locale
**Test URLs**:
Before: https://main--express-website--adobe.hlx.page/tw/express/templates/flyer?lighthouse=on
After: https://ckg-locale-hotfix--express-website--webistry-development.hlx.page/tw/express/templates/flyer?lighthouse=on
> [HOTFIX]: APIs results fix for locales

- express/blocks/shared/masonry.js
- express/blocks/template-list/template-list.js
- express/blocks/template-x/template-x.css
- express/blocks/template-x/template-x.js
- express/scripts/templates.js
- express/styles/styles.css
Description:
Syncing work upstream for API integration work to start
Test URLs:
Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/mwpw-128653/template-x-catalog?lighthouse=on
After: https://mwpw-128653--express-website--wbstry.hlx.page/drafts/qiyundai/mwpw-128653/template-x-catalog?lighthouse=on
> [MWPW-128653] Template X - Syncing work upstream 2

- express/scripts/scripts.js
Fix [MWPW-129831](https://jira.corp.adobe.com/browse/MWPW-129831)
Test URLs:
https://mwpw-129831_2--express-website--adobe.hlx.live/express/create/poster?experiment=ccx0168%2Fchallenger-1
> MWPW-129831 - moving the loading of instrumentation to, after experiment config is created

- express/blocks/bubble-ui-button/bubble-ui-button.js
- express/blocks/floating-button/floating-button.js
- express/blocks/multifunction-button/multifunction-button.js
- express/blocks/shared/floating-cta.css
- express/blocks/shared/floating-cta.js
- express/blocks/sticky-promo-bar/sticky-promo-bar.js
Fix no ticket yet
Added floating button responsiveness to the sticky promo bar through BlockMediator©
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/entitled-homepage-cta?lighthouse=on
- After: https://sticky-promo-bar-x-float-cta--express-website--wbstry.hlx.page/drafts/ernest_sallee/entitled-homepage-cta?lighthouse=on
> [HOTFIX]: Promo Bar X Floating Buttons

- express/blocks/fullscreen-marquee/fullscreen-marquee.css
- express/scripts/scripts.js
Fix: https://jira.corp.adobe.com/browse/MWPW-129904
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-1
- After: https://mwpw-129904--express-website--wbstry.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0039?lighthouse=on
Added a [floating-data spreadsheet](https://adobe.sharepoint.com/:x:/r/sites/CC-Express/_layouts/15/Doc.aspx?sourcedoc=%7BFDADD68A-C592-4A7D-BF92-D616CCF372C1%7D&file=floating-cta-experiments.xlsx&action=default&mobileredirect=true&cid=0a62dddb-e81a-44e9-8a15-1997cc2d4636) for experiment purposes.
If an active experiment is running and a matching experiment ID and challenger ID are found in this sheet, the floating button will be generated from there.
> [MWPW 129904] Experiment Sheet for Floating Button

- express/blocks/bubble-ui-button/bubble-ui-button.js
- express/blocks/floating-button/floating-button.js
- express/blocks/multifunction-button/multifunction-button.js
- express/blocks/shared/floating-cta.js
Description
Fix no ticket yet
Added floating button responsiveness to the sticky promo bar through BlockMediator©
Added support for scrolling floating button interaction
Refactored and centralized the BlockMediator© integration
Test URLs:
Before: https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/entitled-homepage-cta?lighthouse=on
After: https://sticky-promo-bar-x-float-cta--express-website--wbstry.hlx.page/drafts/ernest_sallee/entitled-homepage-cta?lighthouse=on
Regression Check: https://sticky-promo-bar-x-float-cta--express-website--wbstry.hlx.page/express/create/instagram- …
> [HOTFIX]: Promo Bar X Floating Buttons - Follow Enhancement

- express/scripts/instrument.js
Fix SITES-12496
Test URLs:
https://sites-12496--express-website--adobe.hlx.page/express/experiments/ccx0027/quick-action?experiment=ccx0027%2Fchallenger-1
> SITES-12496 - Adding custom events for frictionless quickactions experiment

- express/blocks/make-a-project/make-a-project.css
- express/blocks/promotion/promotion.css
- express/scripts/scripts.js
- express/styles/styles.css
Fixes MWPW-130723
Fixed below items,
- Make a project alignment changes to title and page list.
- Padding for areas in promotions.
- CTA button and making free-plan-widget static and removing animation from the place.
Test URLs:
- Before: https://stage--express-website--adobe.hlx.page/express/beta
- After: https://<branch>--express-website--adobe.hlx.page/express/](https://mwpw-130723--express-website--adobe.hlx.page/express/beta)
> MWPW-130723 | Fixes for Beta Launch Page Enhancements

- express/blocks/template-list-ace/results-modal.js
- express/blocks/template-list-ace/template-list-ace.css
> MWPW-130231 fix safari

- helix-query.yaml
- helix-sitemap.yaml
Fix MWPW-129997
Test Page URLs:
-Before: https://main--express-website--adobe.hlx.page/in/express/feature/image/png
-After: https://mwpw-129997--express-website--adobe.hlx.page/in/express/feature/image/png
Sitemap XMLs
- Before: https://main--express-website--adobe.hlx.page/express/sitemap-other.xml
- After: https://mwpw-129997--express-website--adobe.hlx.page/express/sitemap-other.xml
> MWPW-129997 | Adding India locale specific sitemap config

- express/scripts/templates.js
Fix no ticket
Hide un-QA'd CKG pill on non-en pages as they all need to be translated first.
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/jp/express/templates/logo/text?lighthouse=on
- After: https://unlocalized-pills-fix--express-website--wbstry.hlx.page/jp/express/templates/logo/text?lighthouse=on
> [HOTFIX] CKG Pills: hide untranslated pills on non-us pages

- express/scripts/scripts.js
Fix MWPW-130723
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/in/express/feature/image/png
- After: https://mwpw-129997-analytics--express-website--adobe.hlx.page/in/express/feature/image/png
> MWPW-130723 | Analytics value for pageInfo value for language

- express/blocks/hero-animation/hero-animation.js
- express/blocks/modal/modal.js
- express/blocks/template-list-ace/template-list-ace.js
Give desktop images full size in the hero-animation block
Fix MWPW-131786
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/vhargrave/beta-test?lighthouse=on
- After: [https://MWPW-131786--express-website--adobe.hlx.page/drafts/vhargrave/beta-test](https://hero-animation-large-image--express-website--adobe.hlx.page/drafts/vhargrave/beta-test?lighthouse=on
> MWPW-131786 increase possible width desktop images

- express/blocks/template-list/template-list.js
Fix [mwpw-131924](https://jira.corp.adobe.com/browse/MWPW-131924)
**description**
limiting the scope of props in template-list block so more than 1 of it can live on the same page.
Test URLs:
- After: https://mwpw-131924--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> [MWPW-131924] Scope Limit Template-List props

- express/blocks/template-list/template-list.js
Fix [MWPW-131914](https://jira.corp.adobe.com/browse/MWPW-131914)
Added loadBetterInBackground
Some refactor
**Test URLs:**
- After: https://mwpw-131914--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> [MWPW-131914] Load Better Img in background

- express/blocks/search-marquee/search-marquee.css
- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
- express/scripts/template-redirect.js
- express/scripts/templates.js
Fix [MWPW-131912](https://jira.corp.adobe.com/browse/MWPW-131912)
Test URLs:
- After: https://mwpw-131912--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> [MWPW-131912] Lazy Load templates.js

- express/scripts/scripts.js
Test URLs:
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/templates/flyer/christmas?lighthouse=on
- After: https://mwpw-131912-2--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> update LCP function

- express/blocks/search-marquee/search-marquee.js
- express/blocks/template-list/template-list.css
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer/christmas
- After: https://mwpw-131912-3--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> dynamic load search marquee autocomplete

- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
Fix MWPW-131912-4
Test URLs:
- After: https://mwpw-131912-4--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> [MWPW-131912-4]: attempt to fix CLS opportunities

- express/scripts/gnav.js
This will add new beta related GNAV for home page and non-homepage express pages.
Fix MWPW-132020
Test URLs:
- After: https://mwpw-132020--express-website--adobe.hlx.page/express
> MWPW-132020 | Adding Beta Gnav changes

- express/blocks/search-marquee/search-marquee.js
- express/blocks/template-list/template-list.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
- express/scripts/template-redirect.js
- express/scripts/templates.js
> Template list revamp perf

- express/blocks/hero-animation-beta/hero-animation-beta.css
- express/scripts/gnav.js
Fixing the issue of animation and text overlapping from hero animation block
Fix MWPW-132020
Test URLs:
- After: https://mwpw-132020--express-website--adobe.hlx.page/express/
> MWPW 132020 | Fixing the issue of animation and text overlapping from hero animation block

- express/blocks/hero-animation-beta/hero-animation-beta.css
Fixing animation and text overlap - minimizing text width and button width
Fix MWPW-132089
Test URLs:
- After: https://mwpw-132089--express-website--adobe.hlx.page/express/
> MWPW-132089 | Fixing animation and text overlap - minimizing text width and button width

- express/experiments/ccx0027a/blocks/quick-action2/quick-action.js
**Fix** the event bubbling issue for custom event
As per https://developer.mozilla.org/en-US/docs/Web/API/Event/Event, the default value for `bubble` is false, so explicitly setting it to true
Test URLs:
https://quick-action-event-issue--express-website--adobe.hlx.page/express/spotlight/test/remove-background-new?experiment=ccx0027a%2Fchallenger-1
> fix: Quick action event issue

- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
Fix [MWPW-131458](https://jira.corp.adobe.com/browse/MWPW-131458)
Fixed visible bugs around search bar and toolbar
Tweaked querySelecting for page restructure
Test URLs:
- After: https://mwpw-131458--express-website--wbstry.hlx.page/express/templates/flyer/christmas?lighthouse=on
> [MWPW-131458] Page restructure related fixes

- express/blocks/search-marquee/search-marquee.js
- express/blocks/template-list/template-list.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
- express/scripts/template-redirect.js
- express/scripts/templates.js
Fix [MWPW-132212](https://jira.corp.adobe.com/browse/MWPW-132212)
Search page update to support changed made for template page v2
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/search?tasks=resume&phformat=2:3&topics=colorful&q=colorful&lighthouse=on
- After: https://mwpw-132212--express-website--wbstry.hlx.page/express/templates/search?tasks=resume&phformat=2:3&topics=colorful&q=colorful&lighthouse=on
> [MWPW-132212] Template v2 Search Feature Update

- express/blocks/hero-animation-beta/hero-animation-beta.css
switch colors for the secondary button
Fix MWPW-132089
Test URLs:
- After: https://mwpw-132110--express-website--adobe.hlx.page/express/
> MWPW-132110 switch colors button for tablet view

- express/scripts/gnav.js
> MWPW-132020 new change

- express/blocks/shared/video.js
Fix https://jira.corp.adobe.com/browse/MWPW-132399
Test URLs:
- After: https://mwpw-132399-ios-video--express-website--adobe.hlx.page/drafts/jinglhua/homepage
> Hotfix MWPW-132399 for ios videoModal autoplay

- express/blocks/columns/columns.css
- express/blocks/hero-animation-beta/hero-animation-beta.css
- express/blocks/hero-animation-beta/hero-animation-beta.js
- express/blocks/sticky-promo-bar/sticky-promo-bar.css
- express/blocks/sticky-promo-bar/sticky-promo-bar.js
Fix: https://jira.corp.adobe.com/browse/MWPW-132530
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/casey/beta-homepage/post-launch-mobile-updates?lighthouse=on
- After: https://mwpw-132530-2--express-website--wbstry.hlx.page/drafts/casey/beta-homepage/post-launch-mobile-updates?lighthouse=on
This is a follow-up on this [PR](https://github.com/adobe/express-website/pull/891) and contains fixes 2-5 from the Jira ticket.
> [MWPW 132530-2] Mobile Beta Homepage Enhancements: Part 2 (Mobile)

- express/blocks/template-list/template-list.js
- express/scripts/all-templates-metadata.js
- express/scripts/api-v3-controller.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
Fix https://jira.corp.adobe.com/browse/MWPW-132847
Test URLs:
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/
- After: https://template-list-backward-compatible--express-website--adobe.hlx.page/express/
> Template list backward compatible

- express/scripts/all-templates-metadata.js
- express/scripts/ckg-link-list.js
- express/scripts/content-replace.js
Partial Fix [MWPW-129863](https://jira.corp.adobe.com/browse/MWPW-129863)
- Fixed CKG pill display and SEO page prioritization
- Enhanced Fallback fetch for all templates pages
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer?lighthouse=on
- After: https://mwpw-129863--express-website--wbstry.hlx.page/express/templates/flyer?lighthouse=on
> [MWPW-129863] Template v2 QA round 3

- express/blocks/search-marquee/useInputAutocomplete.js
- express/scripts/all-templates-metadata.js
- express/scripts/content-replace.js
Partial Fix [MWPW-129863](https://jira.corp.adobe.com/browse/MWPW-129863)
Updating all metadata tags for legacy content in hope to achieve more bullet proof backward compatibility.
**Testing issue:**
wbstry branch API call to USS CDN runs into CORS issue(new).
Test **URLs:**
Before: https://template-list-revamp--express-website--adobe.hlx.page/express/templates/flyer?lighthouse=on
After: https://mwpw-129863-1--express-website--wbstry.hlx.page/express/templates/flyer?lighthouse=on
> [MWPW-129863] Template v2 QA round 4

- express/blocks/template-list/template-list.js
> defaulting placeholder format

- express/scripts/all-templates-metadata.js
> replace blades in metadata before page auto update

- express/scripts/content-replace.js
> add missing await

- express/scripts/content-replace.js
> params tasks sanitization

- express/blocks/template-list/template-list.js
Fix https://jira.corp.adobe.com/browse/MWPW-132927
Test URLs:
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/templates/flyer/christmas
- After: https://template-list-category-list-redirect--express-website--adobe.hlx.page/express/templates/flyer/christmas
> categorylist straight redirect

- express/scripts/content-replace.js
Fix '' bleeding into DOM
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/search?tasks=banner&phformat=16:9&topics=%27%27
- After: https://mwpw-129863-7--express-website--adobe.hlx.page/express/templates/search?tasks=banner&phformat=16:9&topics=%27%27
> sanitize task, topic and q

- express/blocks/schemas/schemas.js
This will add webPage schema block to pages. Currently block created needs to be added on the document so that webPage gets added.
this is for testing IN locale with 5 pages.
Once SEO team confirms to go forward with all locales and all pages then the code will get moved to scripts.js
Fix MWPW-130556
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/in/express/feature/image/test-schema-qr-code-generator
- After: https://mwpw-130556--express-website--adobe.hlx.page/in/express/feature/image/test-schema-qr-code-generator
> MWPW-130556 | Adding WebPage Schema

- express/blocks/search-marquee/search-marquee.css
- express/blocks/template-list/template-list.css
Fix https://jira.corp.adobe.com/browse/MWPW-133206
Small layout fixes raised by Vic in the stage->main PR: https://github.com/adobe/express-website/pull/917
**Test URLs:**
- Before: https://stage--express-website--adobe.hlx.page/express/templates?lighthouse=on
- After: https://mwpw-133206--express-website--wbstry.hlx.page/express/templates?lighthouse=on
> [MWPW-133206] fix(template-v2): new extra section padding issue fix + z-index fix

- express/scripts/all-templates-metadata.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
> Temp v2 release fix

- express/scripts/content-replace.js
> catch heroAnimation legacy content replace

- express/scripts/all-templates-metadata.js
Test URLs:
- After: https://hot-fix-locale-seo-nav-title--express-website--adobe.hlx.page/express/
> hotfix seo-nav-title 

- fstab.yaml
https://jira.corp.adobe.com/browse/MWPW-129863
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer/christmas
- After: https://fstab-kr--express-website--adobe.hlx.page/express/templates/flyer/christmas
> Release Templates V2 - fstab for KR

- express/scripts/ckg-link-list.js
- express/scripts/template-redirect.js
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/templates/banner?lighthouse=on
- After: https://redirect-logic-fix-2--express-website--wbstry.hlx.page/de/express/templates/banner?lighthouse=on
> [HOTFIX] ckgpill and redirect logic hotfix

- express/scripts/ckg-link-list.js
- express/scripts/template-redirect.js
https://jira.corp.adobe.com/browse/MWPW-129863
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/it/express/templates/banner
- After: https://fix-ckg-pills--express-website--adobe.hlx.page/it/express/templates/banner
> [Hotfix] Fix ckg pills

- fstab.yaml
https://jira.corp.adobe.com/browse/MWPW-129863
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/
After: https://fstab-bres--express-website--adobe.hlx.page/express/
> Release Templates V2 - fstab for BR+ES

- express/blocks/search-marquee/search-marquee.js
- express/scripts/content-replace.js
- express/scripts/template-redirect.js
Fix https://jira.corp.adobe.com/browse/MWPW-129863
Test URLs:
- After: https://fix-default-redirect--express-website--adobe.hlx.page/express/
> [HOTFIX]fix default redirect

- express/blocks/browse-by-category/browse-by-category.css
https://jira.corp.adobe.com/browse/MWPW-133263
- Removed height: 100% on image
**Test URLs:**
- Before: https://main--express--adobecom.hlx.page/express/templates/
- After: https://mwpw-133263--express--adobecom.hlx.page/express/templates/
> [MWPW-133263] Safari Bug Fix on Browse by Category block

- express/blocks/template-list/template-list.js
Fix [MWPW-133265](https://jira.corp.adobe.com/browse/MWPW-133265)
Remove the "open templates to see animation" from below the toolbar
Test URLs:
- Before: https://stage--express-website--adobe.hlx.page/express/templates/flyer?lighthouse=on
- After: https://mwpw-133265--express-website--wbstry.hlx.page/express/templates/flyer?lighthouse=on
> [MWPW-133265] Template v2 release fix: remove animated text
