adobe/express-website

- express/blocks/columns/columns.js
Relates to https://github.com/adobe/express-website-issues/issues/306
This will allow turning off the floating button (mobile viewport) using the `has-fixed-button` class on the body.
Before: https://main--express-website--adobe.hlx3.page/express/create/logo
After: https://float-button-trigger--express-website--adobe.hlx3.page/express/create/logo?lighthouse=on
> feat(columns): float button based on body class

- express/scripts/scripts.js
Fix https://github.com/adobe/express-website-issues/issues/308
Test: 
1. go to https://issue-308--express-website--adobe.hlx3.page/fr/express/pricing
2. correct price formatting with comma
3. go to https://issue-308--express-website--adobe.hlx3.page/kr/express/pricing?country=fr
4. correct price formatting with comma
> fix(pricing): respect region when formatting price

- express/scripts/scripts.js
* fetch localized `placeholders.json`
* use localized placeholders as `alt` text for `img`s, `title` text for `svg`s
- Icon alt texts 287
- Introduce placeholders 307
- https://placeholders--express-website--adobe.hlx3.page/express/
- https://placeholders--express-website--adobe.hlx3.page/express/pricing
- https://placeholders--express-website--adobe.hlx3.page/dk/express/pricing
- https://placeholders--express-website--adobe.hlx3.page/tw/express/pricing
> fix: placeholders

- express/blocks/columns/columns.css
- express/blocks/columns/columns.js
- express/blocks/shared/video.js
- express/blocks/tutorials/tutorials.css
- express/blocks/tutorials/tutorials.js
Fix https://github.com/adobe/express-website-issues/issues/305
I've imported the identical video player from the tutorials block into the columns block. It seems to follow the specs recommended. 
As per the discussion with Raphael, this functionality is only enabled for highlight column blocks.
I did not add the hover animation as it is marked as optional, and I am struggling to place the overlay due to the div and image have no set height. I will continue to work on this and if PR is not merged by then, I will commit the feature addition.
I feel like the .video-overlay part could potentially be placed within its own global css file and the JS could probably be exported and used globally as well, but for now I restricted myself to only implementing it for this block.
You can test the …
> Columns Highlight: Video implementation

- express/blocks/quick-action-cards/quick-action-cards.css
- express/blocks/quick-action-cards/quick-action-cards.js
Added the action cards block
Fix https://github.com/adobe/express-website-issues/issues/214
- Draft page for testing  the block: `/drafts/rofe/feature/quick-actions`
- The '_See more_' button will appear if there are more than 3 action cards listed.
- The button is reads "_See more_" and "_See less_" using [placeholders](https://github.com/adobe/express-website/pull/305) 
- The Desktop version is following the XD specs: https://xd.adobe.com/view/858f0156-6fe3-441a-8e53-a39cc8be79fc-d0dc/screen/fa5483b0-3d01-4c69-a5b4-2068f5f78f3d/
- The Mobile version also lists 3 cards and then show the _'See more'_ button:
> feat(quick-action-cards): quick action cards block added

- express/blocks/how-to-steps-carousel/how-to-steps-carousel.css
- express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
User reported random image size on page: https://main--express-website--adobe.hlx3.page/drafts/nipun/inform-introduce-engage.
I think all the pages have a similar issue but it gets fixed after 5s when step rotation occurs. Usually, the block is below the folder, i.e. the issue is not visible.
Attempt to fix (including some other pages):
- https://main--express-website--adobe.hlx3.page/drafts/nipun/inform-introduce-engage vs https://fix-carousel-wrong-image-size--express-website--adobe.hlx3.page/drafts/nipun/inform-introduce-engage?martech=off
- https://main--express-website--adobe.hlx3.page/express/create/flyer vs https://fix-carousel-wrong-image-size--express-website--adobe.hlx3.page/express/create/flyer?martech=off
- https://main--express-website--adobe.hlx3.page/express/create/banner …
> fix: review how-to carousel loading and sizing logic

- express/scripts/scripts.js
Wrong currency delimiter:
https://www.adobe.com/express/pricing?country=se
https://www.adobe.com/express/pricing?country=dk
https://www.adobe.com/express/pricing?country=br
vs:
https://price-format-fix--express-website--adobe.hlx3.page/express/pricing?country=se&lighthouse=on
> fix(pricing): price formatting issue

- express/blocks/quick-action-cards/quick-action-cards.css
- express/blocks/quick-action-cards/quick-action-cards.js
Continuation of https://github.com/adobe/express-website/pull/306
XD Spec: https://xd.adobe.com/view/858f0156-6fe3-441a-8e53-a39cc8be79fc-d0dc/screen/fa5483b0-3d01-4c69-a5b4-2068f5f78f3d/
Test URL: https://quick-action-cards--express-website--webistry-development.hlx3.page/drafts/rofe/feature/quick-actions
The first link will remain a button, and the following links will become normal links with a chevron >
Before:
After: 
Please be sure to update the 'learn more' links in authoring to the correct link, I simply copied the same one for testing purposes
> feat('quick-action-cards): ability to add in-line links like 'Learn more'

- express/blocks/pricing-modal/pricing-modal.js
Fix https://github.com/adobe/express-website-issues/issues/310
To test: 
- open https://repair-puf-modal--express-website--adobe.hlx3.page/drafts/alex/pricing?pricing-modal=on
- click on the `Start your 30-day free trial` button
The Word document must contain the `Pricing Modal` block including the correctly formatted content, otherwise, no modal shown.
> fix: connect to pricing column

- express/blocks/quick-action-cards/quick-action-cards.css
Fix bug where show/less button affects other blocks as well.
Test URL: https://quick-action-cards--express-website--webistry-development.hlx3.page/drafts/Abhishek/01-25-2022/quick-actions
Fix: https://github.com/adobe/express-website-issues/issues/313
> fix-bug(quick-action-cards): show more/less affects multiple cards

- express/blocks/how-to-steps/how-to-steps.css
Fix: https://github.com/adobe/express-website-issues/issues/318
https://main--express-website--adobe.hlx3.page/drafts/nipun/education-deployment
vs
https://issue-318--express-website--adobe.hlx3.page/drafts/nipun/education-deployment?lighthouse=on
> fix(how-to-steps): bottom margin too large

- express/scripts/delayed.js
Initializes new Privacy with the correct footer link selector. Clinking on "Cookie Preferences" will show the Preference modal.
https://fix-privacy-modal-link--express-website--adobe.hlx3.page/express/
Allow visitors to update their preferences.
locally
> fix: pass the correct footer selector to Privacy module

- express/blocks/quick-action-cards/quick-action-cards.js
**Issue (reported by Rashmi):**
"Clicking on 'See less' CTA of "Edit your videos" section is redirecting to 'Design made easy for everyone. https://main--express-website--adobe.hlx3.page/drafts/Abhishek/01-25-2022/quick-actions#edit-your-videos"
Fixed by making the 'see less' button reposition you to the top of the block. If it finds a header element directly before the block it will scroll to the top of that header element instead.
**Test URL for the fix**: https://see-less-bug--express-website--webistry-development.hlx3.page/drafts/Abhishek/01-25-2022/quick-actions
> fix(quick-actions-cards): 'see less' now scrolls you to the top of the block

- express/blocks/pricing-columns/pricing-columns.js
add a `title` attribute to the pricing column dropdown, title comes from placeholders
changes to the text content of the title can be changed in the placeholders sheet
fixes [#292](https://github.com/adobe/express-website-issues/issues/292)
- before: https://www.adobe.com/express/pricing
- after: https://pricing-plan-dropdown-label--express-website--adobe.hlx.live/express/pricing?lighthouse=on
> fix: add title attr to pricing column dropdown

- express/scripts/scripts.js
https://safari-img-loading--express-website--adobe.hlx3.page/express/?lighthouse=on
vs. 
https://main--express-website--adobe.hlx3.page/express/?lighthouse=on
suppress extra requests from safari loading unnecessary fall back images
> chore: suppress extra img requests from safari

- express/blocks/hero-animation/hero-animation.css
Fix #327 
https://issue-327--express-website--adobe.hlx3.page/drafts/rofe/hero-dark?lighthouse=on
> chore: use white links in dark option

- express/scripts/scripts.js
`>` is easier to type but blunt looking. Authors should be able to use `›` as well.
> chore: add support for typographic chevron

- express/blocks/inline-banner/inline-banner.css
https://main--express-website--adobe.hlx3.page/drafts/nipun/registration
vs
https://inline-banner-link-color--express-website--adobe.hlx3.page/drafts/nipun/registration?lighthouse=on
(3rd block down)
> feat(inline-banner): indigo links when inverted

- express/blocks/columns/columns.css
This allows using videos with larger dimensions and resizing them for more crispness.
Test URL: https://fullsize-video--express-website--adobe.hlx3.page/express/create/banner?lighthouse=on
cc @skelleyadobe
> chore: fullsize videos to max out at 600x610

- express/scripts/instrument.js
This Pull Request was created in preparation for code review and testing and should not be merged right away. 
(contains no branch urls)
https://branch_tracking--express-website--webistry-development.hlx3.page/express/pricing
(contains branch links)
https://branch_tracking--express-website--webistry-development.hlx3.page/express/create/banner
Feel free to add parameters to the URL in order to test the functionality.
Currently, this implementation will append any filtered parameters to branch links containing `adobesparkpost.app.link` in the URL.
The function will transpose the following parameters to only branch urls meeting the criteria:
| URL Param| Example | Branch Param | Example
| - | - | - | - |
| sdid  | P3KMQSXK | campaign_id  | P3KMQSXK
| ??? | (need more information) | campaign …
> feat(branch): branch url parameter tracking

- express/scripts/scripts.js
https://main--express-website--adobe.hlx3.page/education/express/deployment
vs
https://tel--express-website--adobe.hlx3.page/education/express/deployment?lighthouse=on
(click CTA in marquee)
> fix(links): don't treat tel: links as external

- express/blocks/submit-email/submit-email.css
- express/blocks/submit-email/submit-email.js
Adds an email capture blade as per [this issue](https://github.com/adobe/express-website-issues/issues/325).
Sample content
https://adobe.sharepoint.com/:w:/r/sites/CC-Express/_layouts/15/doc.aspx?sourcedoc=%7Ba848055e-f0c4-42da-8750-9506d1c74267%7D&action=edit
Test URL: https://submit-email-block--express-website--adobe.hlx3.page/express/campaigns/adbemeta-dev?lighthouse=on
Todo:
> feat: submit email block

- express/blocks/submit-email/submit-email.js
JSON body needs to be stringified for signup form.
Wasn't able to see this bug until I could publish because of CORS.
Test URL: https://submit-email-block--express-website--adobe.hlx3.page/express/campaigns/adbemeta-dev?lighthouse=on
> fix: stringify POST body

- express/styles/styles.css
https://main--express-website--adobe.hlx3.page/drafts/nipun/registration#discover-more-tips-on-facebook
vs
https://fb-logo--express-website--adobe.hlx3.page/drafts/nipun/registration?lighthouse=on#discover-more-tips-on-facebook
> feat: use blue facebook logo inside banner

- express/blocks/steps/steps.css
smaller top margin for highlight steps as requested by @skelleyadobe 
https://main--express-website--adobe.hlx3.page/drafts/rassingh/edit/resize
vs
https://steps-top-margin--express-website--adobe.hlx3.page/drafts/rassingh/edit/resize?lighthouse=on
> chore: smaller top margin for steps container

- express/blocks/pricing-columns/pricing-columns.js
This branch was created for the purpose of resolving this issue:
https://github.com/adobe/express-website-issues/issues/330
You can find a test url here:
https://330-beginpurchaseflow--express-website--webistry-development.hlx3.page/express/pricing
I have concerns about launching an async event on submit since I have a feeling in some cases the page will transfer before the function gets to finish, but I am not sure how else to go about it without rewriting most of the code and saving plans locally to avoid fetching them multiple times.
> Issue #330: beginPurchaseFlow event is missing

- .gitignore
Some developers work using IDEs from JetBrains or VS Code Studio and it would be good to be able to git ignore these files in order to avoid accidentally committing them to the project.
> Ignore .idea files related to JetBrains and VS Code Studio IDEs

- express/blocks/columns/columns.js
Paragraphs starting with `*` will be rendered as legal copy. The same should also work for paragraphs starting with `†`.
https://legal-copy-chars--express-website--adobe.hlx.page/express/feature
(scroll down to "take command of social content")
> feat: legal copy can start with * or †

- express/blocks/ratings/ratings.js
Fix ratings block to be wrapped in a function to prevent global variables, and allow more than 1 of the same block on the same page without affecting each other.
Block states:
- [Can't rate](https://ratings--express-website--webistry-development.hlx.page/documentation/block-inventory?action-used=false&action-rated=false&lighthouse=on)
- [Can rate](https://ratings--express-website--webistry-development.hlx.page/documentation/block-inventory?action-used=true&action-rated=false&lighthouse=on)
- [Already rated](https://ratings--express-website--webistry-development.hlx.page/documentation/block-inventory?action-used=true&action-rated=true&lighthouse=on)
Issue fixed: https://main--express-website--adobe.hlx.page/documentation/block-inventory the 2nd block options was affecting the first block …
> fix(ratings): module the block to prevent global variables

- express/blocks/columns/columns.js
The check for video links is too inclusive, it only checks for `/media_` but not the extension. We already have a method for that: `isVideoLink()`.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/55775
- After: https://columns-video-detection--express-website--adobe.hlx.page/drafts/Anuj/55775?lighthouse=on
> fix: video detection too inclusive

- express/scripts/scripts.js
ensure buttons don't have excessive styling like underlines and more
You'll observe that one of the buttons' had underlined text within the button, because Word propagates the underlining through our Pipeline! 
](https://files.slack.com/files-pri/T23RE8G4F-F03F516SVC0/screen_shot_2022-05-06_at_11.39.00_am.png)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/mrosier/instagram-logo-for-business-cards-copy
- After: https://handle-button-underline--express-website--adobe.hlx.page/drafts/mrosier/instagram-logo-for-business-cards-copy?lighthouse=on
> fix(scripts/scripts.js): remove underlines

- express/scripts/bw2.js
- express/scripts/scripts.js
- express/styles/styles.css
- test/unit/bw2.test.js
This is the logic to make Japanese headings wrap at positions so that the lines after word wrapping have more balanced lengths.
Before this change:
After this change:
The logic uses [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) to measure actual text width, decides where to break lines based on the text width and existing `<wbr>` tag locations, and uses CSS style classes to switch on/off the `<wbr>` tags in [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver) callback functions.
**Input:**
- HTML heading element object
- Maximum number of lines to be wrapped into (default value: 6)
**Output:**
The modified heading element object
**Flow of processing:**
**Word wrap level**
Word wrap levels …
> Japanese balanced word wrap

- express/blocks/how-to-steps-carousel/how-to-steps-carousel.css
- express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
- test/unit/blocks/expected/how-to-steps-carousel.section.html
- test/unit/blocks/input/how-to-steps-carousel.doc.html
When adding a link in a tip (inline link and cta button), the link is removed.
On test page: check the tips, they all have at least one link! (missing in the before case).
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/alex/howto?lighthouse=on
- After: https://how-to-step-with-cta--express-website--adobe.hlx.page/drafts/alex/howto?lighthouse=on
> fix(how-to-step-carousel): support cta link with the tip text

- express/blocks/banner/banner.css
Reduce the spacing between a light banner and the next section.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/Anuj/enterprise-nation
- After: https://banner-light-spacing--express-website--adobe.hlx.page/drafts/Anuj/enterprise-nation?lighthouse=on
> chore(banner): remove bottom spacing from light container

- express/scripts/instrument.js
Adding three new Quick Action pages to the checks so that their events are tracked properly. I wonder if in the future this can be added to the analytics sheet as a different sheet possibly.
Test URLs:
https://quick-action-fixes--express-website--webistry-development.hlx3.page/express/feature/image/convert/svg
https://quick-action-fixes--express-website--webistry-development.hlx3.page/express/feature/image/crop
https://quick-action-fixes--express-website--webistry-development.hlx3.page/express/feature/image/qr-code-generator
Look for the quickActionType in contextualData1
> feat(quick-actions): missing quick actions

- express/blocks/make-a-project/make-a-project.js
Some icons are not clickable in the _make a project_ block. This happens when icons are not part of the icon sprite.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/home
- After: https://make-project-icon-fix--express-website--adobe.hlx.page/drafts/rofe/home?lighthouse=on
> fix(make-a-project): some icons not clickable

- express/scripts/scripts.js
Fix https://jira.corp.adobe.com/browse/DOTCOM-65006
Test URLs:
Before: https://main--express-website--adobe.hlx3.page/jp/express/learn/blog/creative-cloud-express-whats-new-font-recommendations
After: https://budoux-disable-ptag--express-website--tamanyan.hlx3.page/jp/express/learn/blog/creative-cloud-express-whats-new-font-recommendations
> fix: stop applying budoux effect to p tags

- express/blocks/shared/video.js
- express/scripts/instrument.js
No issue provided
Test URLs:
- After: https://meta-analytics--express-website--webistry-development.hlx3.page/express/learn/express-your-brand
This branch adds tracking to the following actions:
- Closing a video modal by clicking the x icon
- Closing a video modal by clicking the overlay behind the video
- Closing a video modal by pressing escape
It does not cover the following action:
- Closing a video by removing the hashtag from the url
> feat(analytics): tracking video close

- express/blocks/template-list/template-list.css
images are hidden in block in Safari because the images overflow a container of 0 height
Fix https://github.com/adobe/express-website-issues/issues/346
Test URLs:
- Before in SAFARI: https://www.adobe.com/express/learn/blog/pride-month-zoom-backgrounds-and-lgbtq-posters
- After in SAFARI: https://fix-template-list-bug--express-website--adobe.hlx.page/express/learn/blog/pride-month-zoom-backgrounds-and-lgbtq-posters
> fix(/blocks/template-list/template-list.css):

- express/blocks/shared/carousel.js
- express/blocks/template-list/template-list.js
- express/scripts/instrument.js
No JIRA issue provided for this fix.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/intent-driven-home
- After: https://template-tracking--express-website--webistry-development.hlx3.page/drafts/rofe/intent-driven-home
Analytics tracking was not being extended to the carousel duplicated elements. Additionally, I leveraged the new dispatchEvent system in order to return template-list link tracking back to its original place.
> carousel & template-list analytics fix

- express/blocks/template-list/template-list.css
#448 tried to fix a safari issue but introduced a regression in the hover state animation for all browsers: 
@MarquiseRosier FYI
Test URLs:
- After: https://revert-448--express-website--adobe.hlx.page/express/create/flyer?lighthouse=on
> fix(template-list): regression from #448

- express/blocks/promotion/promotion.css
- express/styles/styles.css
Sometimes you can see an `illustrator` text flashing at the top of the page, which likely stems from the promotion block's unprocessed content. This change ensures that the block stays hidden until fully loaded.
Test URLs:
- Before: https://main--express-website--adobe.hlx.live/express/create/flyer
- After: https://promo-flash--express-website--adobe.hlx.live/express/create/flyer?lighthouse=on
> fix(promotion): hide unprocessed promo block

- express/scripts/scripts.js
When promotion blocks are inserted automatically, the section has class `.section` instead of `section` which causes the block to be rendered with the full window width. This is a regression from #433.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/logo
- After: https://promo-regression--express-website--adobe.hlx.page/express/create/logo?lighthouse=on
> fix(promotion): regression in auto-block code

- express/blocks/puf/puf.css
Fix 2 small issues -> {
`bold text-stroke-color of "Save 17%" #text node`
`checkmark being cut off at the bottom`
}
Test URLs:
- Before: https://mwpw-111453--express-website--adobe.hlx.page/drafts/williambsm/pricing-new
- After: https://mwpw-111453-bold-color--express-website--webistry-development.hlx.page/drafts/williambsm/pricing-new
> fix(puf): bold text-stroke-color of "Save 17%" text node

- express/blocks/columns/columns.css
- express/blocks/columns/columns.js
- express/blocks/hero-animation/hero-animation.css
- express/blocks/hero-animation/hero-animation.js
- express/scripts/scripts.js
- express/styles/blog.css
- express/styles/styles.css
Japanese fonts look visually bigger than English fonts on web pages if they are both specified with the same pixel size.
CCX website does not have specific font sizing CSS styles for localized pages. Hence for the purpose of better page layout on Japanese pages, some font size adjustments are needed.
Main headings (H1 and H2 HTML tags) are the targets for this adjustment.
CCX website has implemented a character count based logic to dynamically change headings' font sizes, which we can leverage to adjust Japanese page font sizes. The logic works in the following way:
- Define a set of different heading font sizes using CSS variables. E.g., `--heading-font-size-xxxl`, `--heading-font-size-m`, `--heading-font-size-s`, etc. The exact font size values are set differently for different screen …
> Jpn font sizing

- express/blocks/columns/columns.css
- express/blocks/columns/columns.js
- express/scripts/scripts.js
- express/styles/styles.css
Legal copy (starting with `*` or `† ` and displayed in smaller type) is currently only supported inside columns blocks. We should make it more universal.
Test URLs (see at the bottom of the hero animation):
- Before: https://main--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-65253/clasroom-accounts
- After: https://legal-copy--express-website--adobe.hlx.page/drafts/Ankush%20hcl37284/DOTCOM-65253/clasroom-accounts?lighthouse=on
> feat: allow legal copy anywhere

- express/blocks/premium-plan/premium-plan.css
Premium plan cards get cut off after first one on mobile.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/pricing
- After: https://premium-plan-fix--express-website--adobe.hlx.page/express/pricing?lighthouse=on
> fix(premium-plan): cards cut off on mobile

- express/blocks/hero-animation/hero-animation.css
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/spotlight/explore
- After: - https://free-plan-fix--express-website--adobe.hlx.page/express/spotlight/explore?lighthouse=on
Cross-check if free plan widget still behaves correctly on other pages:
- https://free-plan-fix--express-website--adobe.hlx.page/express/?lighthouse=on
- https://free-plan-fix--express-website--adobe.hlx.page/express/create/flyer?lighthouse=on
> fix(free-plan-widget): broken on regular hero animation

- express/blocks/blog-posts/blog-posts.css
- express/blocks/list/list.css
align h2 and p elements
h2 and p groups of elements are misaligned! This ensures everything is neat and also expresses hierarchy via indentation of the h2 and p away from the section that follows so they stand out.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/learn/blog
- After: https://fix-alignment--express-website--adobe.hlx.page/express/learn/blog
> refactor(blocks/blog-posts/blog-posts.css):

- express/blocks/puf/puf.css
Fix: issue reported on slack:
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/it/express/pricing
- After: https://puf-icon-fix--express-website--webistry-development.hlx.page/it/express/pricing?lighthouse=on
> fix(PUF): fix icon sizing in PUF block

- express/blocks/branch-io/branch-io.css
Fix ![image](https://user-images.githubusercontent.com/62023521/184246398-dd445c41-8408-46bd-af64-892925135762.png)
- Before: (mobile-only, click on the floating button at the bottom to open the modal):
https://www.adobe.com/express/spotlight/image/remove-background?at_preview_token=2UkyhYTLG4UVqSs5iw814Q&at_preview_index=1_3&at_preview_listed_activities_only=true&at_preview_evaluate_as_true_audience_ids=2033593
> fix(branch-io): move modal from behind the banch banner

- express/styles/blog.css
folks have been reporting some weird alignment and its because of this line
This PR just removes the blanket text-align that overrides even button container styling, and specifies what needs to be centered and what needs to be left-aligned.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/fr/express/learn/blog/tips-improve-linkedin-profile
- After: https://fix-general-left-alignment--express-website--adobe.hlx.page/fr/express/learn/blog/tips-improve-linkedin-profile
- Before: https://www.adobe.com/fr/express/learn/blog/design-youtube-banner
- After: https://fix-general-left-alignment--express-website--adobe.hlx.page/fr/express/learn/blog/design-youtube-banner
- Before: https://www.adobe.com/fr/express/learn/blog/design-event-poster#questions-fr%C3%A9quemment-pos%C3%A9es …
> fix(express/styles/blog.css): fix left align

- express/blocks/app-store-blade/app-store-blade.js
Fix [MWPW-113696](https://jira.corp.adobe.com/browse/MWPW-113696)
Test URLs:
- Before: https://mwpw-113696--express-website--adobe.hlx.page/drafts/qiyundai/create/generic-app-store-blade
- After: 
- Code generated version: https://mwpw-113696--express-website--webistry-development.hlx.page/drafts/qiyundai/create/generic-app-store-blade
- Localizable fragment: https://mwpw-113696--express-website--webistry-development.hlx.page/drafts/qiyundai/create/fragment-app-store-blade
MWPW-113319, the mobile version of this block can also be authored using Fragment. It works out of box!
> fix(app-store-blade): fetch ratings from placeholder instead

- express/scripts/scripts.js
Fixed MWPW-113319
The issue didn't present itself when being developed on two separate branches. Once merged, the blocks got built into the same section and broke the entire auto blocking process. Adding them to the sections to split fixed the issue.
Test URLs:
- Before: https://main--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
> fix(app-store-highlight): adding app store blocks to sections to split

- express/styles/blog.css
p elements are misaligned because of some styling in styles.css, just apply the same styling that happens
to upper sibling in document tree.
- Before: https://www.adobe.com/express/learn/blog
- After: https://fix-view-all-alignment--express-website--adobe.hlx.page/express/learn/blog
> fix(express/styles/blog.css): align p elements

- express/blocks/download-cards/download-cards.css
- bleed `download-card` images of any dimension
Test URLs:
- After: https://mwpw-114266--express-website--adobe.hlx.page/express/
> fix: bleed download card

- express/blocks/columns/columns.css
- express/blocks/hero-animation/hero-animation.css
- express/blocks/hero-animation/hero-animation.js
- express/scripts/scripts.js
- express/styles/styles.css
Fix https://jira.corp.adobe.com/browse/MWPW-116370
Any other language than English, Chinese, Taiwanese or Korean will get a stacked layout on desktop to leave enough room for the CTA text:
Test URLs:
- German homepage
- Before: https://main--express-website--adobe.hlx.page/de/express/
- After: https://mwpw-116370--express-website--adobe.hlx.page/de/express/?lighthouse=on
- German create page
- Before: https://main--express-website--adobe.hlx.page/de/express/create/logo
- After: https://mwpw-116370--express-website--adobe.hlx.page/de/express/create/logo?lighthouse=on
- German feature page
- …
> fix: stack free plan widget for long CTAs

- express/blocks/choose-your-path/choose-your-path.css
The text on the mouse "bubble" can run out of bounds:
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/fr/express/paths
- After: https://path-mouse-text--express-website--adobe.hlx.page/fr/express/paths?lighthouse=on
> fix(choose-your-path): keep mouse text inside bubble

- express/blocks/ratings/ratings.js
- express/scripts/instrument.js
Fix [MWPW-116099](https://jira.corp.adobe.com/browse/MWPW-116099)
Test URLs:
- After: https://mwpw-116099--express-website--webistry-development.hlx.page/express/feature/image/remove-background
This PR aims to add multiple segments to allow rating on different quick action pages. I suggest that in the future maybe we should migrate the segments array to either a dedicated sheet, or a metadata row.
You can test the different pages by referring to the segments on the JIRA task and adding/removing …
> [MWPW-116099] Enable multiple rating segments

- express/blocks/hero-3d/hero-3d.css
- use % instead of vw to fix scrollbar issue on windows browsers
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/design-app
- After: https://mwpw-114266--express-website--adobe.hlx.page/express/design-app
> fix: change width unit

- express/blocks/floating-button/floating-button.js
When there is a buggy 'empty section' above the hero, the floating button wasn't working correctly. 
Test URLs:
- After: https://main--express-website--webistry-development.hlx.page/express/
.
- Before: https://main--express-website--adobe.hlx.page/express/learn/express-your-brand
- After: https://main--express-website--webistry-development.hlx.page/express/learn/express-your-brand
.
- After: https://main--express-website--webistry-development.hlx.page/express/create/flyer
.
buggy page:
- Before: https://main--express-website--adobe.hlx.live/express/create/flyer
- After: https://main--express-website--webistry-development.hlx.live/express/create/flye …
> fix(floating-button): fix the bug with floating-button when there is an empty section above the hero

- express/blocks/floating-button/floating-button.js
Fix any potential bugs with the sections due to the floating wrapper being at the top of `main` by moving the floating button to the bottom instead.
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/
After: https://main--express-website--webistry-development.hlx.page/express/
.
Before: https://main--express-website--adobe.hlx.page/express/learn/express-your-brand
After: https://main--express-website--webistry-development.hlx.page/express/learn/express-your-brand
.
Before: https://main--express-website--adobe.hlx.page/express/create/flyer
After: https://main--express-website--webistry-development.hlx.page/express/create/flyer
> fix(floating-button): move to the bottom of main instead of the top

- express/blocks/split-action/split-action.css
- express/blocks/split-action/split-action.js
Fix https://jira.corp.adobe.com/browse/MWPW-117208
Test URLs:
- After: https://mwpw-117208--express-website--webistry-development.hlx.page/express/feature/image/remove-background
- Sliding down the quick action menu now redirects to the action.
- Clicking on the "stay on web" call to action now redirects to the action.
- Clicking on the background image behind the quick action split now redirects to the action.
- Adjusted the z-index in order to hide the promotional banner when necessary. …
> [MWPW-117208] Fix quick action split issues

- express/blocks/hero-3d/hero-3d.js
Currently download icons are added based on button text, which doesn't work well for i18n. I propose to always add a download icon to a button on a download card, unless its parent is an `<em>` (italic in Word).
(This PR also removes the invisible download icon from the Microsoft store badge, keeping it more centered.)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/design-app
- After: https://download-card-i18n-fix--express-website--adobe.hlx.page/de/express/design-app
> fix(hero-3d): append download icon to all except italic CTAs

- express/blocks/how-to-steps/how-to-steps.css
override margin on top of h3
blog posts have additional margin that interfere with block styling! 
BLOG Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/learn/blog/cool-pfp-for-instagram
- After: https://fix-how-to-step--express-website--adobe.hlx.page/express/learn/blog/cool-pfp-for-instagram
MAIN Test URLs:
MAIN:
Before: https://main--express-website--adobe.hlx.page/express/create/video/intro/wedding
After: https://fix-how-to-step--express-website--adobe.hlx.page/express/create/video/intro/wedding
Before: https://main--express-website--adobe.hlx.page/express/create/logo/fortnite
After: https://fix-how-to-step--express-website--adobe.hlx.page/express/create/logo/fortnite
Before: https://main--express-website--adobe.hlx.page/express/feature/design/add-icons …
> fix(blocks/how-to-steps/how-to-steps.css): tmp fix

- express/blocks/floating-button/floating-button.js
Fix https://jira.corp.adobe.com/browse/MWPW-117101
Test URLs:
- After: https://mwpw-117101--express-website--webistry-development.hlx.page/express/create/flyer
The scroll down button on the floating-button block has been adjusted. It would be worth while testing on all of the following urls as well:
https://main--express-website--adobe.hlx.page/express/
https://main--express-website--adobe.hlx.page/express/learn/express-your-brand
https://main--express-website--adobe.hlx.page/express/learn/students …
> [MWPW-117101] - Fixing the scroll interaction on floating-button block

- fstab.yaml
Allow mapping of international URLs.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/jp/express/templates/flyer/christmas
- After: https://map-lang-folders--express-website--adobe.hlx.page/jp/express/templates/flyer/christmas?lighthouse=on
> chore: map non-english templates folders

- express/scripts/scripts.js
The plans comparison learn more button suffers from lazy-loading images shifting content while scrolling, therefore making the final destination of the scrolling incorrect. Removing smooth scrolling for just this feature to prevent that from happening.
Fix plans comparison
Test URLs:
- After: https://learn-more-fix--express-website--webistry-development.hlx.page/drafts/qiyundai/create/social-media-graphic
> fix: remove smooth scrolling for better locating

- express/scripts/instrument.js
Fix https://jira.corp.adobe.com/browse/MWPW-120155
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/feature/video/animate/audio
- After: https://mwpw-120155--express-website--webistry-development.hlx.page/express/feature/video/animate/audio?lighthouse=on
Added extra quick action analytics to the CTA buttons on the pages listed in the JIRA issue.
Someone with access to analytics will have to test this. I pre-emptively added the quick action contextual data since sooner or later it would come along as a request.
> feat(analytics): add tracking for new quick action pages

- express/experiments/ccx0074/blocks/toc1/toc.css
- express/experiments/ccx0074/blocks/toc2/toc.css
> [@skelley](https://cq-dev.slack.com/team/WAPELB17Y) flagged a bug in the Table of Contents experience that needs addressing:
> ![File](https://user-images.githubusercontent.com/1235810/200897830-5440b00e-202f-4256-82b3-721f104cfc0b.jpg)
> When the Table of Contents is present, the bobbing arrow in the bottom CTA should be removed. Would that be possible to update in the code for the experiment? that applies to both Ch1 and Ch2
Test URLs:
- After: https://fix-toc--express-website--adobe.hlx.page/express/create/flyer
> fix: floating button in ToC challengers

- express/experiments/ccx0074/blocks/toc1/toc.css
- express/experiments/ccx0074/blocks/toc2/toc.css
When the ToC experiments for CCX0074 are open, the overlay is sitting below the white gradient background of the floating button. This PR addresses the issue
Before/after:
Test URLs:
- After:
- https://fix-toc-background--express-website--adobe.hlx.live/express/create/flyer?experiment=ccx0074%2Fchallenger-1
- https://fix-toc-background--express-website--adobe.hlx.live/express/create/flyer?experiment=ccx0074%2Fchallenger-2
> fix: adjust ToC overlay background to hide floating button background

- express/blocks/steps/steps.css
- express/icons/animate-character.svg
Single file icons are rendered as `img.icon` which in case of the `steps` block are rendered at 24px instead of 40px.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/video/animation
- After: https://steps-icon-fix--express-website--adobe.hlx.page/express/create/video/animation?lighthouse=on
> fix(steps): fix img.icon size

- express/styles/styles.css
- Long words in headings can spill over, those should be broken with hyphens.
- Long button texts get cut off, those should be wrapped to a second line instead
@skelleyadobe  @timliu-adobe 
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/feature/content-scheduler
- After: https://overflow-fix--express-website--adobe.hlx.page/drafts/rofe/feature/content-scheduler?lighthouse=on
> fix: break long words and don't clip button texts

- express/scripts/templates.js
- package-lock.json
Increasing the limit of the templates 
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/de/express/templates/banner/twitter-header
- After: https://templates-limit-fix--express-website--webistry-development.hlx.page/de/express/templates/banner/twitter-header?lighthouse=on
This page specifically doesn't work on the main branch due to the 1,000 limit, whereas on my branch link it will work because the limit is now 100,000.
> feat(templates): allow up to 10,000 rows

- express/blocks/shared/background-animations.js
- express/blocks/template-list/template-list.css
Fix templates-list holiday variant: Changing the way of authoring background animation from name to video url (no ticket)
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer1
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/flyer2
- After: https://animation-by-url--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer1?lighthouse=on
- After: https://animation-by-url--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer2?lighthouse=on
> fix(templates-list): change animation intake method

- express/blocks/link-list/link-list.css
Fix Collaboration Hub (no-ticket)
The link list doesn't have the expected compatibility with the layout of other blocks in collaboration hub pages. Adding a leftalign variant to be combo-used with fullwidth.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/DOTCOM-76478/collaboration-hub
- After: https://collab-hub-fix--express-website--webistry-development.hlx.page/drafts/ernest_sallee/DOTCOM-76478/collaboration-hub?lighthouse=on
> fix(link-list): fullwidth leftalign variant

- express/blocks/app-store-blade/app-store-blade.css
Fix App Store Blade (no ticket)
The App Store Blade flexbox was buggy on Safari. Resorting to using inline-blocks.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/post/instagram
- After: https://app-blade-fix--express-website--webistry-development.hlx.page/express/create/post/instagram?lighthouse=on
> fix(app-store-blade): replacing a flexbox with inline-blocks

- express/styles/styles.css
Removing the extra lateral padding helps minimize hyphenation on mobile.
Test URLs:
- Before: https://www.adobe.com/es/express/create/business-card/dj
- After: https://no-wrapper-padding--express-website--adobe.hlx.page/es/express/create/business-card/dj?lighthouse=on
> chore: remove horizontal wrapper padding on mobile

- express/blocks/puf/puf.js
This is what the pricing page randomly looks like on mobile:
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/pricing
- After: https://fix-puf--express-website--adobe.hlx.page/express/pricing?lighthouse=on
> fix: PUF block is followed by a huge whitespace on mobile

- express/blocks/floating-button/floating-button.js
- express/scripts/scripts.js
Feat [MWPW-119933](https://jira.corp.adobe.com/browse/MWPW-119933)
Test URLs:
Before:
https://main--express-website--adobe.hlx.page/drafts/qiyundai/auto-multifunction-button
https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer
https://main--express-website--adobe.hlx.page/drafts/qiyundai/auto-floating-button
https://main--express-website--adobe.hlx.page/drafts/qiyundai/auto-overwriting-multifunction-button
https://main--express-website--adobe.hlx.page/express/create/logo
After:
https://mwpw-119933-redo--express-website--webistry-development.hlx.page/drafts/qiyundai/auto-multifunction-button?lighthouse=on
https://mwpw-119933-redo--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer?lighthouse=on …
> fix(auto-multifunction-button): async bug fix

- express/blocks/plans-comparison/plans-comparison.js
- express/scripts/instrument.js
Fix https://jira.corp.adobe.com/browse/MWPW-122224
In this Pull Request, I am adding specific button ID tracking to the home page only as requested urgently by the Analytics team. 
Please note that this is only temporary for until we figure out how to generate button ID’s. This code will eventually be removed.
In the future I would suggest that we find a more complete and compatible solution to this as it is not productive to have the development team have to maintain specific button ids (for example, when the homepage changes, I will have to come in and make those changes reflect here, and then there is the question of localisation).
The events have been mapped out by following [this specific document](https://adobe.sharepoint.com/:x:/r/sites/CCXGrowthTeam/Shared%20Documents/Analytics/Exp …
> Express Homepage ButtonID Analytics

- express/scripts/scripts.js
Media links mistakenly get deocrated as buttons, resulting in a wrong floating CTA.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/tw/express/create/flyer
- After: https://v7-regression--express-website--adobe.hlx.page/tw/express/create/flyer?lighthouse=on
> fix: no buttons for blob store links

- express/scripts/instrument.js
No JIRA ticket was issued as it is a very quick and easy change to make.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/feature/video/animate/audio
- After: https://quick-action-analytics--express-website--webistry-development.hlx.page/express/feature/video/animate/audio?lighthouse=on
- Before: https://main--express-website--adobe.hlx.page/express/create/video/animation
- After: https://quick-action-analytics--express-website--webistry-development.hlx.page/express/create/video/animation?lighthouse=on
> [Quick Action] Fix quickActionType on two analytics events

- express/blocks/template-list/template-list.js
Fix (free-in-app-badge). No ticket. Free-in-app badge will now hide if 'free-in-app' is not defined in local placeholder sheet.
Test URLs:
Before:
https://main--express-website--adobe.hlx.page/express/create/card
https://main--express-website--adobe.hlx.page/fr/express/create/card
After:
https://free-tag-fix--express-website--webistry-development.hlx.page/express/create/card?lighthouse=on
https://free-tag-fix--express-website--webistry-development.hlx.page/fr/express/create/card?lighthouse=on
> fix(free-in-app-badge): Don't display empty badge

- express/scripts/instrument.js
- express/scripts/scripts.js
As part of a PoC for Hemingway, we want to track image views via a generic data layer so that the alloy instrumentation can pick those events up async.
Test URLs:
- Before: https://main--express-website--adobe.hlx.live/express/create/flyer
- After: https://hemingway-poc--express-website--adobe.hlx.live/express/create/flyer?lighthouse=on
> feat: basic image views tracking on the data layer

- express/scripts/templates.js
No JIRA ticket provided, this is a fix to allow authors to preview and hopefully update the default templates page without issue.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/default
- After: https://template-default-fix--express-website--webistry-development.hlx.page/express/templates/default?lightouse=on
> fix(templates): allow access to staging default

- express/blocks/fullscreen-marquee/fullscreen-marquee.js
Add Auto Generated Floating Button(existing feature as in Columns block). No ticket.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/ernest_sallee/youtube-fullscreen-marquee
- After: https://mwpw-119277-fix--express-website--webistry-development.hlx.page/drafts/ernest_sallee/youtube-fullscreen-marquee?lighthouse=on
> [MWPW-119277] Fullscreen Marquee fix: Add auto generated floating button

- express/blocks/floating-button/floating-button.css
- express/blocks/floating-button/floating-button.js
Fix spreadsheet MFB. No ticket.
During the process of development for spreadsheet based multifunction button, the multifunction portion was split into its own block of function. The missing lottie player wasn't noticed due to the fact that all testing pages had their floating button block to begin with. This is to make sure even a page doesn't have a floating button, a multifunction button will load its own lottie player.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/agenda/meeting
- After: https://mwpw-119933-fix--express-website--webistry-development.hlx.page/express/create/agenda/meeting?lighthouse=on
> fix(spreadsheet MFB): load lottie player for multifunction button explicitly

- express/scripts/templates.js
There is no JIRA issue provided for this feature request (made by me!)
You can use `?dev=true|on|yes` in order to toggle the dev sheet, and this can only happen in the staging environment.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer/christmas
- After (without dev sheet): https://templates-dev--express-website--webistry-development.hlx.page/express/templates/flyer/christmas?lighthouse=on
- After (with dev sheet): https://templates-dev--express-website--webistry-development.hlx.page/express/templates/flyer/christmas?lighthouse=on&dev=on
You can find the development templates spreadsheet here:
https://adobe.sharepoint.com/:x:/r/sites/CC-Express/Shared%20Documents/website/templates-dev.xlsx?d=w1fb1e30b06ca476997165b2a85a3bf0e&csf=1&web=1&e=Fz6JCa
> Templates SEO developer testing sheet

- express/blocks/template-list/template-list.css
No ticket. Fix requested by Tim. Added extra margin right for RR title text to make room for TOC 
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/menu
- After: https://fix-toc-overlap--express-website--webistry-development.hlx.page/express/create/menu?lighthouse=on
> fix(relevant-rows): add margin to template title when toc is present

- express/blocks/template-list/template-list.css
- express/blocks/template-list/template-list.js
No ticket.
Remove word-breaks
Adding toc placeholder to make text wrap around TOC.
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/create/menu
After: https://fix-toc-overlap--express-website--webistry-development.hlx.page/express/create/menu?lighthouse=on
> fix(relevant-rows): TOC overlap with Template List title fix take 2

- express/scripts/scripts.js
Fix word wrap degrade issue. It occurred because the PR https://github.com/adobe/express-website/pull/502 updated budoux-index-ja.min.js.
Add `budoux` class to disable budoux on small screens
https://github.com/adobe/express-website/blob/main/express/styles/styles.css#L966-L976
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/jp/express/
- After: https://fix-word-wrap-degradation--express-website--tamanyan.hlx.page/jp/express/?lighthouse=on
- [fix: disable budoux styles of h1 to h5 on small screens](https://github.com/adobe/express-website/pull/331)
> fix: word wrap degrade issue

- express/blocks/template-list/template-list.js
Fix template-list category list -> filter conflict, no ticket.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/search?tasks=flyer&phformat=2:3&topics=flower
- After: https://template-search-hotfix--express-website--webistry-development.hlx.page/express/templates/search?tasks=flyer&phformat=2:3&topics=flower&lighthouse=on
> fix(template-list): search task correction after fetching counts

- express/blocks/app-store-blade/app-store-blade.js
- express/blocks/app-store-highlight/app-store-highlight.js
- express/blocks/fragment/fragment.js
- express/blocks/plans-comparison/plans-comparison.css
- express/blocks/plans-comparison/plans-comparison.js
- express/blocks/template-list/template-list.js
- express/scripts/scripts.js
Proactive Fix PR: Since we started using auto generated blocks, the decorateMain() function call inside fragment blocks have been trying to render auto blocks for as many extra times as the amount of fragments being used on the page. Loading plain html doesn't stop the auto blocks from loading as the fragment main is loaded on the same URL, which triggers the metadata powered auto blocks.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/card
- After: https://duplicate-app-block--express-website--webistry-development.hlx.page/express/create/card?lighthouse=on
> fix(duplicate-autoblock): Inject Auto Blocks only to enclosing <main>

- express/blocks/icon-list/icon-list.js
Pre-priocessed icons get replaced again and potentially broken.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/nonprofits
- After: https://icon-list-bug--express-website--adobe.hlx.page/express/nonprofits?lighthouse=on
> fix(icon-list): pre-processed icons garbled

- express/scripts/instrument.js
Fix https://jira.corp.adobe.com/browse/MWPW-123031
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/create/poster
After: https://mwpw-123031--express-website--webistry-development.hlx.page/express/create/poster?lighthouse=on
This is an emergency hotfix to rollback the overide on contextualData1.
> [MWPW-123031] Button ID analytics emergency hotfix

- express/blocks/quick-action-card/quick-action-card.css
Fix https://jira.corp.adobe.com/browse/MWPW-123315
Test URLs:
- Before: https://main--express-website--webistry-development.hlx.page/drafts/casey/quick-action-card/resize
- After: https://mwpw-123315-2--express-website--webistry-development.hlx.page/drafts/casey/quick-action-card/resize?lighthouse=on
Added auto-hyphenation to the text on the carousel to avoid the overflow that was occurring in some languages.
> [MWPW-123315] Quick Action Cards - Hyphens on carousel text

- express/scripts/scripts.js
When Contentsquare is loaded through Adobe Launch, Contentsquare looks at the ttMETA object. Populating the ttMETA object with Franklin experiment details. This is to validate Contentsquare integration on stage environment
Fixes - [SITES-11885](https://jira.corp.adobe.com/browse/SITES-11885)
Test URLs:
https://contentsqaure-integration-stage--express-website--adobe.hlx.page/express/
> feat: Contentsqaure integration on stage

- express/blocks/quick-action-card/quick-action-card.css
No ticket.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/nl/express/fragments/quick-action-card/generic
- After: https://hyphen-safari-fix--express-website--webistry-development.hlx.page/nl/express/fragments/quick-action-card/generic
> fix(quick-action-card): hyphen on safari

- express/blocks/pricing-hub/pricing-hub.js
Fix https://jira.corp.adobe.com/browse/MWPW-122824
Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/pricing
After: https://pricing-hotfix--express-website--webistry-development.hlx.page/express/pricing?lighthouse=on
I fixed the scroll so that the cards wouldn't be hidden by the gnav when scrolling up. It's recommended to disabled CORS security in order to review this change as the global nav doesn't load on the Webistry testing branches.
I have otherwise tested the functionality and it works appropriately for me.
> hotfix[pricing-hub]: fix the scroll to account for the gnav

- express/blocks/plans-comparison/plans-comparison.css
- express/blocks/plans-comparison/plans-comparison.js
Fix [MWPW-122680](https://jira.corp.adobe.com/browse/MWPW-122680)
- Added dynamically changing color to the free plan header icon (template + lightning), active=white, inactive=black
- Hide plans comparison during rendering to avoid showing a broken block
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/create/flyer?lighthouse=on
- After: https://mwpw-122680--express-website--webistry-development.hlx.page/express/create/flyer?lighthouse=on
> [MWPW-122680] Plans Comparison: Dynamic Header Icon Color

- express/experiments/ccx0027/blocks/quick-action1/quick-action.css
- express/experiments/ccx0027/blocks/quick-action2/quick-action.css
- adding pointer-events to none on the converted image so that users can't right click and dowonload
- fix style issues
Fix [SITES-11254](https://jira.corp.adobe.com/browse/SITES-11254)
Test URLs:
https://quick-action-embed-frictionless--express-website--ravkiran.hlx.page/express/experiments/ccx0027/quick-action?experiment=ccx0027%2Fchallenger-1
> fix: prevent right click and download for the image and style issues

- express/blocks/quick-action/shared.js
- express/experiments/ccx0027/blocks/quick-action1/quick-action.css
- express/experiments/ccx0027/blocks/quick-action1/quick-action.js
- express/experiments/ccx0027/blocks/quick-action2/quick-action.css
due to the `cclqt-remove-background` occupying the 100% of container, the experience is broken 
As a fix, setting the height for `cclqt-remove-background` while counting 50px for download button container above the utility.
Fix [SITES-11254](https://jira.corp.adobe.com/browse/SITES-11254)
Test URLs:
https://frictionless-c1-height--express-website--ravkiran.hlx.page/express/feature/image/remove-background?experiment=ccx0027%2Fchallenger-1
> fix: adjusting the height of utility in c1 so that it doesn't break into the next section

- express/scripts/scripts.js
When Contentsquare is loaded through Adobe Launch, Contentsquare looks at the ttMETA object. Populating the `ttMETA` object with Franklin experiment details.
Fixes - [SITES-11885](https://jira.corp.adobe.com/browse/SITES-11885)
Test URLs:
https://contentsqaure-integration--express-website--adobe.hlx.live/express/
I couldn't find a page where Franklin experiment is running now, so just used the /express/, please let me know if there's a page, then I can update the Test Urls.
> feat: adding content square tracking vars to franklin experiments

- express/scripts/scripts.js
https://helix-env-update--express-website--adobe.hlx.live/express/?lighthouse=on
vs.
https://main--express-website--adobe.hlx.live/express/?lighthouse=on
> chore: update to use textContent

- express/experiments/ccx0027/blocks/quick-action1/quick-action.css
- express/experiments/ccx0027/blocks/quick-action1/quick-action.js
- express/experiments/ccx0027/blocks/quick-action2/quick-action.css
- express/experiments/ccx0027/blocks/quick-action2/quick-action.js
Fix: adding legal copy to variants
Test URLs:
https://quickaction-legal-copy--express-website--adobe.hlx.page/express/feature/image/remove-background?experiment=ccx0027%2Fchallenger-1
> fix: adding legal copy to the quick action test variants

- express/scripts/templates.js
Fix: https://jira.corp.adobe.com/browse/MWPW-122517
As the metadata is stored in the [metadata](https://adobe.sharepoint.com/:x:/r/sites/CC-Express/_layouts/15/Doc.aspx?sourcedoc=%7BFE02F0B2-26AC-46D1-A433-795157A3B92F%7D&file=metadata.xlsx&action=default&mobileredirect=true&cid=8d4ebe03-26c2-4094-806c-bdcc718b7769) for templates pages, it was not being added to the breadcrumbs. This fix extracts the 'short-title' from the metadata sheet and adds it into the metadata of the page.
Test URLs:
- Before: https://main--express-website--webistry-development.hlx.page/express/templates/flyer/christmas?lighthouse=on
- After: https://breadcrumbs-templates--express-website--webistry-development.hlx.page/express/templates/flyer/christmas?lighthouse=on
> feat(breadcrumbs-templates): Extracted short-title

- express/blocks/template-list/template-list.js
No ticket. This is to fix a small bug noticed during the working session with the localization team.
To test: go to the before and after page, and make any search using the search bar. The before should land on a 404 while the after should give you a search page
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/br/express/templates/flyer?lighthouse=on
- After: https://search-locale-fix--express-website--webistry-development.hlx.page/br/express/templates/flyer?lighthouse=on
> [No Ticket]: fix url prefix for localized search pages

- express/blocks/shared/floating-cta.js
- express/blocks/split-action/split-action.js
No ticket. Fixing:
- Type of Event dispatched by floating button can't contain detail
- The function attaching events is now containable
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/feature/image/resize?lighthouse=on
- After: https://split-action-fix-2--express-website--webistry-development.hlx.page/express/feature/image/resize?lighthouse=on
> [HOTFIX] Split Action: Fixing Rendering Issue with Floating Button

- express/scripts/instrument.js
Fix [MWPW-129831](https://jira.corp.adobe.com/browse/MWPW-129831)
**Problem & Solution**
Current instrumentation logic, is finding the links from the existing DOM and attaching the `trackButtonClick` event listener for the links. Sometimes, when the experiment is running, the DOM Is loaded after the event listeners are attached in the instrument.js, so these links are missing the tracking. As a fix, changed the listening on the document and call `trackButtonClick` if the `event.target` is anchor tag
Test URLs:
https://mwpw-129831--express-website--adobe.hlx.page/express/create/poster
> MWPW-129831 - Franklin experimentation link tracking issue

- express/scripts/utils.js
- test/unit/scripts/utils.test.js
Fix [MWPW-130160](https://jira.corp.adobe.com/browse/MWPW-130160)
Test URLs:
- After: https://debounce-throttle-memoize--express-website--adobe.hlx.page/express/
**A benign PR that creates utils.js and fill it with util functions and unit tests. Util functions like debounce, throttle, and memoize are needed and used for implementing Autocomplete [here](https://github.com/adobe/express-website/commit/48b200d28ba4006522637fe7e49a28c0a80d81ae#diff-97eb231bc102882b26ebf76f1e9088b590dcb63ff5b9de6744186b4e6897601d). Once this is merged, I'll update that branch and rebase on main.**
- If you folks prefer, I can also split them into 3 separate files.
- In the future efforts of reducing the size of scripts.js, we can move more …
> feat(debounce-throttle-memoize): utils.js

- express/scripts/scripts.js
no ticket. Tweaking the live column behavior to authors' preference -- no button rendered instead of rendering a default one if live column is 'N'.
Test note: This actually cannot be tested on staging link as the live=N guard only works on prod.
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/create/instagram-story?dev=on&lighthouse=on
- After: https://fcta-n-fix--express-website--webistry-development.hlx.page/express/create/instagram-story?dev=on&lighthouse=on
> [HOTFIX] Floating CTA: remove default reference on autoBlock building

- express/scripts/templates.js
No ticket. Turns out the active redirecting from templates.js doesn't work and it's considered a bug from the pipeline. Reverting changes to reduce the huge sheet load.
Test note: nothing to test. staging result not representative of the prod behavior.
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/templates/announcement?lighthouse=on
- After: https://revert-redirect--express-website--webistry-development.hlx.page/express/templates/announcement?lighthouse=on
> [HOTFIX]: Removed non-functioning redirect to reduce sheet load

- express/blocks/template-list/template-list.js
No ticket. The ES template-list results are showing the total count in old thousand separator format. Using space instead as a special treatment for now.
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/templates/?lighthouse=on
- After: https://es-number-fix--express-website--wbstry.hlx.page/express/templates/?lighthouse=on
> [HOTFIX]: Template List -  language specific results fix 3

- express/blocks/columns/columns.js
- express/blocks/hero-animation/hero-animation.js
Fix: https://jira.corp.adobe.com/browse/MWPW-129072
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/nonprofits
- After: https://mwpw-129072--express-website--wbstry.hlx.page/express/nonprofits?lighthouse=on
The 'Watch Video/Now' buttons on the page contained an href which was returning a 404 error to Google Search. Added a 'no-follow' attribute to the a tags. Sharon will let us know once this is merged if it fixes the issues she is seeing from the SEO side.
> [MWPW 129072] Broken href on buttons

- express/experiments/ccx0027a/blocks/quick-action2/quick-action.js
- express/scripts/instrument.js
Issue: when the ccl-quick-action rendering is delayed but instrument.js is loaded and executed, then `cclQuickAction.length` will be 0, so further events will not fire. To fix this, introduced a new event `ccl-quick-action-rendered`, if the rendering is already complete, then the existing flow will take care, otherwise, an event listener will be registered to handle the events async.
Fix quick action race condition
Test URLs:
https://quick-action-race-condition--express-website--adobe.hlx.page/express/spotlight/test/remove-background-new?experiment=ccx0027a%2Fchallenger-1
> fix: race condition between instrument.js and ccl-quick-action rendering

- express/scripts/google-yolo.js
Fix [MWPW-131922](https://jira.corp.adobe.com/browse/MWPW-131922)
Google YOLO are now by default suppressed on viewports smaller than 900px. This configuration can be overwritten by setting the page metadata **mweb-google-yolo** to one of: [yes, true, on, Y].
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/beta?lighthouse=on
- After: https://mwpw-131922--express-website--wbstry.hlx.page/express/beta?lighthouse=on
> [MWPW-131922]: [mobile] Google YOLO investigation and suppression

- express/scripts/scripts.js
ticket to follow
Added the ability to suppress floating CTA for a certain audience using non-block words in the desktop/mobile column. (recommend something verbose. i.e. 'no-button', 'N/A')
As long as the name in the cell is not one of the valid version of the floating-cta, the button won't load for that url.
This sheet contains the 
https://adobe.sharepoint.com/:x:/r/sites/CC-Express/_layouts/15/Doc.aspx?sourcedoc=%7BFBD7F903-4C71-4BF5-AB07-E44143691889%7D&file=floating-cta-dev.xlsx&action=default&mobileredirect=true&cid=9193a015-081b-4f29-983a-df44ffb55be1 
**Test URLs:** …
> [BETA] Floating-CTA: Add suppression power to floating-cta sheet

- express/scripts/gnav.js
Preparing for stage to main sync up without latest Beta Gnav changes
Test URLs:
- After: https://stage-without-gnav--express-website--adobe.hlx.page/express/
> Preparing for stage to main sync up without latest Beta Gnav changes

- express/scripts/gnav.js
Putting back beta gnav changes for launch preparation
Test URLs:
- After: https://stage-with-beta-gnav-back--express-website--adobe.hlx.page/express/
> Putting back beta gnav changes for launch preparation

- express/scripts/gnav.js
Fix https://jira.corp.adobe.com/browse/MWPW-132589
Test URLs:
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/templates/flyer/christmas
- After: https://template-v2-no-gnav-breadcrumbs--express-website--adobe.hlx.page/express/templates/flyer/christmas
> suppress gnav breadcrumbs for templates

- express/blocks/template-list/template-list.js
Fix MWPW-129863-2
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/search?tasks=facebook%20post&phformat=2:3&topics=christmas
- After: https://mwpw-129863-2--express-website--adobe.hlx.page/express/templates/search?tasks=facebook%20post&phformat=2:3&topics=christmas
> [MWPW-129863] stop expecting ratios to always be specified

- express/blocks/template-list/breadcrumbs.js
Test URLs:
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/
- After: https://template-list-breadcrumbs-trailing-slashes--express-website--adobe.hlx.page/express/
> add trailing slash to breadcrumbs

- express/blocks/search-marquee/search-marquee.js
Resolve [MWPW-133057](https://jira.corp.adobe.com/browse/MWPW-133057)
The search marquee now has the ability to send the searched text to a log sheet(find in the bottom of this PR). As a temporary solution, we'll be doing this in a 'fire and forget' fashion. There could be delayed/missed submissions in tracking but the search feature won't be affected.
To test, fire a random search then go to the log sheet and watch the new row appear with the keyword you put in the search bar.
**Test URLs:**
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/temp …
> [MWPW-133057] Search Marquee Keyword Tracking

- express/blocks/long-text/long-text.css
- express/blocks/long-text/long-text.js
Fix [MWPW-133097](https://jira.corp.adobe.com/browse/MWPW-133097)
A barebone version of the long-text block. If neither a heading or a paragraph is authored (the entire block having no text), the block will remove either the wrapper, or the block itself if the immediate parent is the section container.
**Test URLs:**
- Before: https://template-list-revamp--express-website--adobe.hlx.page/express/templates/search?tasks=banner&phformat=2:3&topics=christmas
- After: https://mwpw-133097--express-website--wbstry.hlx.page/express/templates/search?tasks=banner&phformat=2:3&topics=ch …
> [MWPW-133097] Long Text Block - 1st Iteration

- express/blocks/search-marquee/search-marquee.js
- express/blocks/template-list/template-list.js
For template v2 launch
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer?lighthouse=on
- After: https://search-tracking-improvement--express-website--wbstry.hlx.page/express/templates/flyer?lighthouse=on
> feat(search-tracking): adding audience and mobile support

- express/scripts/content-replace.js
> Reduce tbt

- express/blocks/schemas/schemas.js
Related to https://github.com/adobe/express-website/pull/912 (with 2 approvals)
This will add webPage schema block to pages. Currently block created needs to be added on the document so that webPage gets added.
this is for testing IN locale with 5 pages.
Once SEO team confirms to go forward with all locales and all pages then the code will get moved to scripts.js
Fix MWPW-130556
Test URLs:
- Before: https://stage--express-website--adobe.hlx.page/in/express/feature/image/test-schema-qr-code-generator
- After: https://main--express-website--adobe.hlx.page/in/express/feature/image/test-schema-qr-code-generator
> MWPW-130556 | Adding WebPage Schema (#912)

- express/blocks/browse-by-category/browse-by-category.css
- express/blocks/template-list/breadcrumbs.js
- express/blocks/template-list/template-list.css
- express/scripts/ckg-link-list.js
https://jira.corp.adobe.com/browse/MWPW-133170
Fixed css of browse-by-category and template-list horizontal variant.
By default and unless falsy specified in metadata sheet, searchMarquee will show CKG pills
When short-title is missing, breadcrumbs won't have an empty lastCrumb
Test URLs:
- Before: https://stage--express-website--adobe.hlx.page/fr/express/
- After: https://template-v2-fixes--express-website--adobe.hlx.page/fr/express/
> [To Stage] Template v2 fixes

- express/blocks/template-list/breadcrumbs.js
- express/scripts/all-templates-metadata.js
- express/scripts/content-replace.js
- express/scripts/scripts.js
> Template v2 release fixes

- express/scripts/ckg-link-list.js
> [Pre-release fix] wrap linklist generation in condition to prevent script blocking error

- express/scripts/gnav.js
Invoking stage specific IMS domain on stage URLs. This would fix the redirection to production IMS on click of sign in and hence do not get redirected to prod page rather than stays on stage domain
Fix MWPW-132350
Test URLs:
- After: https://MWPW-132350--express-website--adobe.hlx.page/express/
> MWPW-132350 | Invoking stage specific IMS domain on stage URLs

- express/blocks/browse-by-category/browse-by-category.css
- express/blocks/template-list/breadcrumbs.js
- express/blocks/template-list/template-list.js
- express/scripts/gnav.js
Test URLs:
- After: https://stage--express-website--adobe.hlx.page/express/
> Merge Stage to Main

- fstab.yaml
Fix [mwpw-133266](https://jira.corp.adobe.com/browse/MWPW-133266)
It's exposed that some rows in the fstab.yaml are obsolete. Here's a quick PR to remove them from the file.
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/express/templates/flyer?lighthouse=on
- After: https://mwpw-133266--express-website--wbstry.hlx.page/express/templates/flyer?lighthouse=on
> [MWPW-113266] fstab clean up

- express/scripts/ckg-link-list.js
Fix [MWPW-133351](https://jira.corp.adobe.com/browse/MWPW-133351)
**Dscription**
A couple things were changed last minute during the release. Some of these changes caused a low-exposure regression on the CKG pill. There's the quick fix for it.
Fixes includes: 
- If existing SEO pages are found, they should be prepended (prioritized)
- If no translated name found for non-EN search pages, hide the pill.
**Test URLs:**
- Before: https://main--express-website--adobe.hlx.page/jp/express/templates/flyer/donation?lighthouse=on
- After: https://mwpw-133351--express-website--wbstry.hlx.page/jp/express …
> fix(untranslated-ckg-pills): metadata key fix & CKG pill altText logic fix

- express/blocks/template-list/template-list.js
Fix [MWPW-133513](https://jira.corp.adobe.com/browse/MWPW-133513)
Fix mistakenly hard-lowercased FR words in grammar template
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/fr/express/templates/?lighthouse=on
- After: https://mwpw-133513--express-website--wbstry.hlx.page/fr/express/templates/?lighthouse=on
> [MWPW-133513] FR toolbar title case fix

- express/blocks/search-marquee/search-marquee.js
Fix [MWPW-133739](https://jira.corp.adobe.com/browse/MWPW-133739)
Search Marquee will now launch search as soon as a prediction result is clicked
users can also use tab key and enter key to interact with the search results now
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/?lighthouse=on
- After: https://mwpw-133739--express-website--wbstry.hlx.page/express/templates/?lighthouse=on
> [MWPW-133739] Templates v2 Search Marquee: Launch search on prediction click

- express/blocks/search-marquee/autocomplete-api-v3.js
Fix https://jira.corp.adobe.com/browse/MWPW-134006
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/express/templates/?lighthouse=on
- After: https://stage--express-website--adobe.hlx.page/express/templates/?lighthouse=on
Should have 0 impact on the Autocomplete for EFGJ languages
For all other languages, no network request should be sent for autocomplete, like in https://stage--express-website--adobe.hlx.page/es/express/templates/
> Autocomplete only for EFGJ
